@startmindmap
title =<i><size:18>[[docs/AI-ML-DL-Data-Science-and-BigData/data-science/data-engineering/data-pipeline/gif/change-data-capture.adoc Change Data Capture (CDC)]] gif
!theme hacker

* Change Data Capture (CDC)
** Definition
*** <size:12>**Change Data Capture** is the process of identifying and capturing changes made to **data** in **source systems,** allowing **real-time or near-real-time replication and synchronization** with **target systems.**

** Objectives
*** Real-Time Data Updates
****[#yellow] <i><size:12>Capture and apply changes to **data** immediately as they occur.
*** Data Synchronization
****[#yellow] <i><size:12>Keep target systems up-to-date with source system changes.
*** Minimize Latency
****[#yellow] <i><size:12>Reduce the time between **data** changes and their replication.

**[#lime] CDC Techniques
***[#gold] <i><b>Log-Based CDC
****[#yellow] <i><size:12>Capture changes from **database** transaction logs.
***[#orange] <i><b>Trigger-Based CDC
****[#yellow] <i><size:12>Use **database** triggers to capture changes.
***[#pink] <i><b>Polling-Based CDC
****[#yellow] <i><size:12>Periodically poll source systems to identify changes.

** CDC Tools
*** Debezium
****[#yellow] <i><size:12>An open-source **CDC** platform supporting multiple **databases**.
*** Apache Kafka Connect
****[#yellow] <i><size:12>Connectors for **CDC** with integration into Apache Kafka.
*** AWS Database Migration Services (DMS)
****[#yellow] <i><size:12>A managed service for **CDC** and **database** migrations.

**[#a] Considerations
*** Data Source Compatibility
****[#yellow] <i><size:12>Ensure that source systems support the chosen **CDC** technique.
***[#orange] <i><b>Data Volume
****[#yellow] <i><size:12>Plan for scalability to handle high **data** volumes in real-time.
*** Data Schema Changes
****[#yellow] <i><size:12>Address challenges related to schema changes in source systems.

*** Data Security
****[#yellow] <i><size:12>Implement encryption and access controls to secure captured changes.

** Best Practices
*** Data Schema Evolution
****[#yellow] <i><size:12>Plan for schema changes and evolution in the target systems.
*** Data Validation
****[#yellow] <i><size:12>Implement validation checks to ensure the integrity of replicated **data**.
*** Error Handling
****[#yellow] <i><size:12>Develop robust error handling and conflict resolution mechanisms.
*** Monitoring and Alerting
****[#yellow] <i><size:12>Set up continuous monitoring and alerting for **CDC** processes.

@endmindmap
