@startmindmap
title =<b><i><u>Asynchronous System</u> Use Case Modeling; <<Publisher>> & <<Subscriber>>
* ===<b><i>[[docs/3-programming-languages/Venkat-Subramaniam/synchronous-system-use-case-modeling-full-details.puml Synchronous System Use Case Modeling]] full details OneNote Notebook
** <b><i>[[https://guides.visual-paradigm.com/developing-a-new-e-commerce-platform-with-use-case-2-0-a-comprehensive-guide/ Developing a New E-commerce Platform with Use Case 2.0: A Comprehensive Guide]]
*** <b><i>[[https://www.visual-paradigm.com/scrum/user-story-splitting-vertical-slice-vs-horizontal-slice/ User Story Splitting - Vertical Slice vs Horizontal Slice]]

*:<img:images/img_206.png{scale=.7}>
<img:images/img_207.png{scale=.807}>
;
@endmindmap
