@startmindmap
title =<i><b><u>Integration Style\n<img:images/img_74.png{scale=.6}>

*:<img:images/img_176.png{scale=1.20}>
<img:images/img_177.png{scale=1.20}>
<img:images/img_178.png{scale=1.20}>;
@endmindmap
