@startmindmap
title =<i><size:18><b>Legal Interactions
!theme hacker

*[#darkblue] <i><color #white> Types of <b>Legal Interactions
**[#lightblue] <i><color #black><size:12>Routine <b>Legal Matters
***[#yellow] <i><color #black>Obtaining <b>Legal Advice
***[#yellow] <i><color #black>Signing Contracts
***[#yellow] <i><color #black>Drafting <b>Legal Documents
**[#lightblue] <i><color #black><size:12>Law Enforcement Encounters
***[#yellow] <i><color #black>Police Questioning
***[#yellow] <i><color #black>Arrests
***[#yellow] <i><color #black>Searches and Seizures
**[#lightblue] <i><color #black><size:12><b>Legal Proceedings
***[#yellow] <i><color #black>Court Hearings
****[#gold] <i><color #black>Criminal Trials
****[#gold] <i><color #black>Civil Trials
***[#yellow] <i><color #black>Arbitration or Mediation
***[#yellow] <i><color #black>Administrative Proceedings
**[#lightblue] <i><color #black><size:12><b>Legal Representation
***[#yellow] <i><color #black>Hiring a Lawyer
***[#yellow] <i><color #black><b>Legal Aid Services
***[#yellow] <i><color #black>Self-Representation (Pro Se)
**[#lightblue] <i><color #black><size:12><b>Legal Obligations
***[#yellow] <i><color #black>Compliance with Laws and Regulations
***[#yellow] <i><color #black>Fulfilling Contractual Obligations
***[#yellow] <i><color #black>Responding to <b>Legal Notices
**[#lightblue] <i><color #black><size:12><b>Legal Disputes
***[#yellow] <i><color #black>Civil Litigation
****[#gold] <i><color #black>Contract Disputes
****[#gold] <i><color #black>Property Disputes
****[#gold] <i><color #black>Personal Injury Claims
***[#yellow] <i><color #black>Criminal Prosecution
****[#gold] <i><color #black>Charges and Defense
****[#gold] <i><color #black>Plea Bargaining
****[#gold] <i><color #black>Sentencing
**[#lightblue] <i><color #black><size:12><b>Legal Rights
***[#yellow] <i><color #black>Right to <b>Legal Counsel
***[#yellow] <i><color #black>Right to Remain Silent
***[#yellow] <i><color #black>Right to Due Process
***[#yellow] <i><color #black>Right to Fair Trial
***[#yellow] <i><color #black>Right to Appeal
***[#yellow] <i><color #black><b>Other Legal Protections
****[#gold] <i><color #black>Right to Privacy
****[#gold] <i><color #black>Freedom of Expression
****[#gold] <i><color #black>Right to Equality
****[#gold] <i><color #black>Right to Access Justice
@endmindmap
