@startmindmap
title =<i><b><u><size:18>The illustrated guide to PhD
!theme hacker


*[#darkblue] <i><color #white>The illustrated \n<i><color #white>guide to PhD
**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_767.png Which area should I join from computer science?]]
***[#grey] |<#lime><i><color #black><size:18><b>[[docs/3-programming-languages/Venkat-Subramaniam/current-year-plan.puml Current Year Plan &  Time-Table]]|<#red><color:white><i><size:18><b>[[docs/3-programming-languages/Venkat-Subramaniam/My-Rights-in-Legal-Interactions-in-Pakistan.puml My (individual) Rights in a Legal Interactions in Pakistan]]|

**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_65.png What is PhD?]]
***[#green]:<b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_65.png What does it Mean to Have a PhD:]]
*<b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_65.png Myths of Specialization and Departmental Expertise]];
****[#yellow] <i><color #black><size:12>**1- Myth:** A PhD in your subject of specialization makes you the expert of the entire area i.e. department to which that subject specialization belongs.
****[#yellow] <i><color #black><size:12>**2- Myth:** PhDs are department specific specializations. Hence, a PhD faculty can only serve in the department of his specialization. [departmental turf wars].
****[#a] <i><color #black><size:12><b>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_65.png Myth-1: A PhD specialization belonging to a particular departmental area makes you an expert of that area!]]
***[#green] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_65.png By the time you finish "elementary school", you know a little:]]

***[#green] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_66.png By the time you finish "high school", you know a bit more: ]]
***[#green] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_67.png With a "bachelor's degree", you gain a specialty: ]]
***[#green] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_781.png A master's degree (MS) deepens that specialty: ]]
***[#green]:|<#red><b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_782.png Reading research papers takes you to the edge of human knowledge:]]|
====
|<#grey><b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_809.png How to absorb textbooks like a sponge?]]|
|<#grey><b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_810.png AI Prof. Wah Uni (PhD student & Data structures & algorithm design]] \n\t<b><i><color #red>* <size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_812.png Algorithm research areas]]|
|<#grey><b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_810.png AI Prof. Wah Uni (AI, Databases, & Data-science, ML & other fields)]]|
|<#grey><b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_811.png Goal Setting and Planning (Programming Tip by Tim Buchalka)]]|;
****[#a] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_782.png Once you're at the boundary, you focus:]]
****[#a] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_783.png You push at the boundary for a few years:]]
*****[#black] |<#red><b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_785.png Linus Torvalds pushing at the boundary for a few years?]]|
****[#a] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_783.png Until one day, the boundary gives way:]]
****[#a] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_783.png And, that dent you've made is called a Ph.D.:]]
****[#green] |<#red><b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_784.png Of course, the world looks different to you now:]] |
*****[#black] |<#red><b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_785.png So, don't forget the bigger picture: & Keep pushing]]|


@endmindmap
