@startmindmap
title =<i><b><u>[[docs/3-programming-languages/Venkat-Subramaniam/gif/API-vs-SDK.adoc WebService & API as Integration (integrating with a webservice)]]
caption <img:images/image-2023-02-20-18-57-28-106.png{scale=.66}>

!theme hacker

*[#darkblue]:<i><color #white>[[docs/3-programming-languages/clean-architecture/images/external-interfaces-or-APIs.png WebService]]  & <size:12>[[docs/3-programming-languages/clean-architecture/images/image-2023-02-20-18-57-28-106.png (S/W Project Cost Estimation Technique based on Use Case Points) click me]]
|<#red><b><i>[[docs/2-uml/requirements-and-design-with-plantuml/1-use-cases-or-features/use-case.png Nature of Use-Case & Actor vs Use-Case & webservice]] click me|
|<img:images/img_470.png{scale=.94}>|
|<img:images/img_469.png{scale=.96}>|
|<img:images/img_471.png{scale=.838}>|;
**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_428.png Front-end]] \n*<i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_574.png DDD]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_428.png User Interface]] \n*<b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_574.png DDD]]
****[#a] <i><color #white><b><size:12>[[docs/1-Requirement-Engineering/MVP-PoC-and-case-study/UI-UX.puml UI/UX mindmap]]
***[#green] <b><i><color #white><size:12>Client-side Logic
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_428.png UI Components]] \n*<i><color #black><size:12><b>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_574.png DDD]]
****[#yellow] <i><color #black><size:12>Forms
****[#yellow] <i><color #black><size:12>Buttons
****[#yellow] <i><color #black><size:12>Input Fields
**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/images/img_7.jpg Back-end]]
***[#green] <b><i><color #white><size:12>Server-side Logic
***[#green] <b><i><color #white><size:12>Database
****[#yellow] <i><color #black><size:12>SQL Database
****[#yellow] <i><color #black><size:12>NoSQL Database
****[#yellow] <i><color #black><size:12>Data Models
**[#lightblue] <i><color #black><size:12>APIs
***[#green] <b><i><color #white><size:12>RESTful APIs
****[#darkorange] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc Authentication]]
*****[#a] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc 12 Tips for API Security]]
****[#darkorange] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/session-JWT-Token-SSO-and-OAuth-2-0.adoc Authorization]]
*****[#a] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc 12 Tips for API Security]]
****[#yellow] <i><color #black><size:12>Endpoint 1
****[#yellow] <i><color #black><size:12>Endpoint 2
**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc Security]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc SSL/TLS]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc Encryption]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc Firewalls]]
**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/4-K8-service-type.adoc Scalability]]
***[#green] <b><i><color #white><size:12>Load Balancing
***[#green] <b><i><color #white><size:12>Caching
***[#green] <b><i><color #white><size:12>Replication
**[#lightblue] <i><color #black><size:12>Monitoring
***[#green] <b><i><color #white><size:12>Logging
***[#green] <b><i><color #white><size:12>Metrics
***[#green] <b><i><color #white><size:12>Alerts
**[#lightblue] <i><color #black><size:12>HTTP Methods
***[#green] <b><i><color #white><size:12>GET
***[#green] <b><i><color #white><size:12>POST
***[#green] <b><i><color #white><size:12>PUT
***[#green] <b><i><color #white><size:12>DELETE



*[#darkblue] <i><color #white>[[docs/3-programming-languages/clean-architecture/images/external-interfaces-or-APIs.png APIs as Integration]] \n<img:images/img_471.png{scale=1}>
**[#lightblue] <i><color #black><size:12>RESTful APIs
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/session-JWT-Token-SSO-and-OAuth-2-0.adoc Authentication]]
****[#darkorange] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/session-JWT-Token-SSO-and-OAuth-2-0.adoc OAuth]]
****[#darkorange] <b><i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/session-JWT-Token-SSO-and-OAuth-2-0.adoc JWT]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/session-JWT-Token-SSO-and-OAuth-2-0.adoc Authorization]]
****[#yellow] <i><color #black><size:12>Role-based Access
****[#yellow] <i><color #black><size:12>Permissions
***[#green] <b><i><color #white><size:12>Endpoint 1
****[#yellow] <i><color #black><size:12>Description
****[#yellow] <i><color #black><size:12>Parameters
****[#yellow] <i><color #black><size:12>Response
***[#green] <b><i><color #white><size:12>Endpoint 2
****[#yellow] <i><color #black><size:12>Description
****[#yellow] <i><color #black><size:12>Parameters
****[#yellow] <i><color #black><size:12>Response
**[#lightblue] <i><color #black><size:12>SOAP APIs
***[#green] <b><i><color #white><size:12>WSDL
***[#green] <b><i><color #white><size:12>SOAP Envelope
***[#green] <b><i><color #white><size:12>Endpoint
***[#green] <b><i><color #white><size:12>Operations
**[#lightblue] <i><color #black><size:12>GraphQL
***[#green] <b><i><color #white><size:12>Schemas
***[#green] <b><i><color #white><size:12>Queries
***[#green] <b><i><color #white><size:12>Mutations
**[#lightblue] <i><color #black><size:12>API Gateways
***[#green] <b><i><color #white><size:12>Traffic Routing
***[#green] <b><i><color #white><size:12>Rate Limiting
***[#green] <b><i><color #white><size:12>Transformation
**[#lightblue] <i><color #black><size:12>API Documentation
***[#green] <b><i><color #white><size:12>Swagger/OpenAPI
****[#yellow] *<b><i><color #black><size:12>Read: So that You can "Use" it to integrate with the existing APIs \n*<b><i><color #black><size:12>Write(Create): So that others can "use" it to integrate with your API/service
***[#green] <b><i><color #white><size:12>API Reference
***[#green] <b><i><color #white><size:12>Interactive API Console
**[#lightblue] <i><color #black><size:12>API Monitoring
***[#green] <b><i><color #white><size:12>Health Checks
***[#green] <b><i><color #white><size:12>Performance Metrics
***[#green] <b><i><color #white><size:12>Error Tracking
**[#lightblue] <i><color #black><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc API Security]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc API Keys]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc Rate Limiting]]
***[#green] <b><i><color #white><size:12>[[docs/3-programming-languages/Venkat-Subramaniam/gif/api-design-and-security-best-practices.adoc Input Validation]]

@endmindmap
