@startmindmap
title =<b><i>Types of API Integration\n<img:images/img_1.png>\n<size:18><i><color:pink>The spectrum of "contract types" from "strict to lose"
!theme hacker

*[#darkblue] =<color:white><i>Types of API Integration\n<img:images/img.png{scale=.72}>\n<color:white><i>Architecture styles define how different components of an \n<color:white><i>application programming interface (API) interact with one another.
**[#lightblue] <i><color #blac><size:14>Synchronous
***[#green] <b><i><color #white><size:14>REST
****[#yellow] <i><color #black><size:14>SOAP
****[#yellow] <i><color #black><size:14>JSON-RPC
****[#yellow] <i><color #black><size:14>XML-RPC
***[#green] <b><i><color #white><size:14>GraphQL
***[#green] <b><i><color #white><size:14>gRPC
***[#green] <b><i><color #white><size:14>Custom
**[#lightblue] <i><color #blac><size:14>Asynchronous
***[#green] <b><i><color #white><size:14>Webhooks
***[#green] <b><i><color #white><size:14>Websockets
***[#green] <b><i><color #white><size:14>Event-Driven
****[#yellow] <i><color #black><size:14>Pub/Sub
****[#yellow] <i><color #black><size:14>Message Queue
****[#yellow] <i><color #black><size:14>Streaming API

@endmindmap
