@startmindmap
title =<i><u>Preface
*:<img:images/img.png{scale=1}>
==<i><b><size:22><u>What are the things which remain unchanged in Computer Science?==
<img:images/img_5.png{scale=1.3}>;
@endmindmap
