@startmindmap
title =<i><u>Lecture "39, 40, 41, 42 & 43 continue" What happens when I click on a program? \n<i><u><b><size:20>How is memory allocated for 32bit architecture processor program? \n<i>Virtual university
* <i><b>[[docs/books/1-books-backlog/operating-system/operating-system.puml Granularity bit]] memory paging & segmentation "O/S concept"
** <i><b>[[docs/books/1-books-backlog/computer-architecture/what-happens-when-I-click-on-a-program.puml What happens when I click on a program? \nHow is memory allocated for 32bit architecture processor program?]]

* a
@endmindmap