@startmindmap

!theme hacker
title =__ JSON (JavaScript Object Notation)__

* **JSON (JavaScript Object Notation)** \n<img:images/img.png{scale=.7}>
** Lightweight Data Interchange Format
**[#pink] Key-Value Pairs
***[#gold] **"key": value**
**[#pink] Data Types
*** Number
*** String
*** Boolean
*** Object
*** Array
*** Null
**[#pink] Nested Structures
*** Objects inside Objects
*** Arrays inside Objects or Arrays
**[#gold] **Example**
***[#pink] {
***   "name": "John Doe",
***   "age": 30,
***   "isStudent": false,
***[#pink]   "address": {
***     "street": "123 Main St",
***     "city": "New York",
***     "country": "USA"
***[#pink]   },
***   "interests": ["programming", "reading", "music"]
***[#pink] }
** Common Usage
*** Data Exchange between Systems
*** Configuration Files
*** Web APIs (RESTful APIs)
** Tools and Libraries
*** Parsing and Serialization
**** JSON.parse()
**** JSON.stringify()
*** JSON Schema Validation
**** JSON Schema
**** AJV, JSON.NET, Joi
@endmindmap
