@startmindmap
title = __//**Online open source mind-map apps**//__

*[#a] ===Online open source mind-map apps
** =**[[https://markmap.js.org/repl#?d=gist%3Aaf76a4c245b302206b16aec503dbe07b markmap online interactive mind-map app, click me to follow the link]]** \n<img:images/img_1.png>

@endmindmap
