@startmindmap
title = __ Technical Writing 101__

* Technical Writing 101
** The Technical Writing Profession
*** Types of Technical Writing
*** The Role of a Technical Writer
** The Technical Writing Process
*** Planning
**** Determining the Purpose and Audience
**** Developing a Project Plan
**** Creating a Writing Schedule
*** Researching
**** Gathering Information
**** Analyzing the Information
**** Organizing the Information
*** Writing
**** Creating a First Draft
**** Editing and Revising
**** Formatting and Design
*** Reviewing
**** Peer Review
**** Expert Review
**** User Review
*** Publishing
**** Preparing for Publication
**** Choosing the Right Format
**** Delivering the Document
**[#a] =Writing Skills
*** ===Grammar and Punctuation
***[#yellow] ==Style and Tone
*** Writing for the Web
@endmindmap
