@startmindmap

title =<b><i><u>Why am I sad, unhappy, unfulfilled, & tired?
!theme hacker

*[#darkblue] Desire/Wants
**[#lightblue] Highest want: Create Facebook like site & build company
***[#green] <b><i><color #white><size:14>This is impossible
**[#lightblue] Want:Build a software house (service/product) base & CMM-level 5
***[#green] <b><i><color #white><size:14>This is impossible
**[#lightblue] Desire: Become expert in your field (top 10%)
***[#green]:<b><i><color #white><size:14>This is possible
==<b><i><color #white><size:14>But become what?==
<b><i><color #white><size:14>Software architect, enterprise architect, BA, PM, Cloud architect, frontend developer, backend developer, fullstack developer, android developer, ios developer, Kubernetes extension, docker expert,
<b><i><color #white><size:14>linux expert, database developer, DevOps engineer, DevSecOps engineer, platform engineer, MlOps engineer, gitOps engineer, data engineer, data scientist, data analyst, UI/UX engineer, game developer
<b><i><color #white><size:14>etc.;
***[#green] <b><i><color #white><size:14>Keep getting 10 or 20 dollar jobs
@endmindmap
