@startmindmap
title =Liberalism

skinparam node {
    BackgroundColor LightBlue
    BorderColor Navy
}

* Liberalism
** Definition
*** Political and social philosophy
*** Individual rights and freedoms
*** Market-based economies
*** ==Simple test to test yourself to check if you are liberal
**** Do you think the people should 've the liberty to choose their own **government? (Yes/No)**
**** Do you think the people should 've the liberty to choose their own **religion? (Yes/No)**
**** Do you think the people should 've the liberty to choose their own **profession? (Yes/No)**
**** Do you think the people should 've the liberty to choose their own **spouse? (Yes/No)**
***** Meaning you support <size:24>**LGBTQ+**
****[#yellow] If you answer **yes** to all questions, congratulations you are a **liberal**
****[#yellow] = In the big ideological war of the 20th century Liberalism came on the top, \neven conservatives are liberal in the long run

** Key Figures
*** John Locke
*** Adam Smith
*** John Stuart Mill

** Types of Liberalism
*** Classical Liberalism
*** Modern Liberalism
*** Libertarianism

** Principles
*** Individual liberty
*** Rule of law
*** Limited government

** Economic Policies
*** Free-market capitalism
*** Protection of private property
*** Minimal government intervention

** Social Policies
*** Civil liberties
*** Equality and diversity
*** Social safety nets

** Historical Development
*** Enlightenment era
*** Influence on democratic systems

** Criticisms
*** Economic inequality
*** Lack of social safety nets
*** Erosion of traditional values
@endmindmap
