@startmindmap
title = __7 Habits of Highly Effective People__

* Paradigms
** Paradigm shift
** Principle-centered living
** **Character ethic** vs. **personality ethic**

* Habits
** **Dependence to independence**
***[#pink] **Private victories**
**** Be proactive
**** Begin with the end in mind
**** Put first things first
**[#yellow] **Independence to interdependence**
***[#pink] **Public victories**
**** Think win-win
**** Seek first to understand, then to be understood
**** Synergize
**[#yellow] **Continuous improvement**
*** Sharpen the saw

* Principles
** Natural laws
** Universal principles

* Conclusion
** Balancing and renewing resources
** **The 8th habit**

@endmindmap
