@startmindmap
'!theme hacker

title = __Prophet Muhammad Family Tree__\nForefathers of Hazrat Muhammad


* Adam\n* Father of Humankind

** Idris (Enoch)\n* Prophet of Knowledge

***:Nuh (Noah)
* Built the Ark (ship)
* **Second father of humankind (Adam-e-sani)**
According to Islamic tradition and other Abrahamic
religious texts like the Bible, Prophet Nuh was
chosen by God to build an ark to save a select
group of people and animals from a devastating
flood that was sent as a punishment for the
widespread corruption and disbelief of the people
of his time. Nuh's story of building the ark and
the survival of those on board serves as a symbol
of God's mercy, the importance of faith, and the
consequences of disobedience.;

****:Hud
* Sent to 'Ad'
Ad was an ancient Arabian tribe or community
mentioned in Islamic tradition. Prophet Hud
is known for his role in calling the people
of 'Ad to monotheism and righteousness,
similar to other prophets in the list who
were sent to guide their respective communities.;

*****:Saleh
** Sent to Thamud
Thamud was an ancient Arabian tribe or community
mentioned in Islamic tradition. Prophet Saleh is
known for his role in calling the people of
Thamud to believe in the oneness of God and to
abandon their sinful and oppressive practices.
Like other prophets, Saleh was a messenger of
guidance and a warner to his people.;

******:Lut (Lot)
* Sent to Sodom
In the Abrahamic religious traditions, the story
of Prophet Lut is often associated with his
mission to guide the people of Sodom and Gomorrah
away from sinful and immoral behavior. The people
of these cities were engaged in acts of
wickedness, and Lut's role as a prophet was to
call them to righteousness and monotheism, and to
warn them about the consequences of their sinful
actions. His story carries moral and ethical
lessons about the consequences of sinful behavior
and the importance of following God's guidance.;

*******:Ibrahim (Abraham)
** Father of Monotheism
*** Isma'il (Ishmael)
*** Ishaq (Isaac);

********:Ismail (Ishmael)
** Father of the Arab People;

*********[#lime]:Muhammad (Peace Be Upon Him)
** The Final Prophet;


********:Ishaq (Isaac)
** Son of Ibrahim;

*********:Yaqub (Jacob)
** Son of Ishaq
*** Yusuf (Joseph);

**********:Yusuf (Joseph)
** The Dream Interpreter;

***********:Ayyub (Job)
** Patience in Suffering;

************:Shu'ayb
** Sent to Midian;

*************:Dhulkifl (Ezekiel)
** Identity is unclear;

**************[#yellow]:Musa (Moses)
** Led the Exodus;

***************[#yellow]:Dawud (David)
** The Psalmist
*** Sulayman (Solomon);

****************:Sulayman (Solomon)
** Wise and Powerful;

*****************:Ayyub (Job)
** Patience in Suffering;

******************:Yunus (Jonah)
** Swallowed by a Whale;

*******************[#gold]:Zakariya (Zechariah)
** Father of Yahya (John the Baptist);

********************[#gold]:Yahya (John the Baptist)
** **Announced the Coming of Isa**;

*********************[#yellow]:**Isa (Jesus)**
** Born of the Virgin Mary
*** Maryam (Mary);

********************** =In Year 1922\n<img:images/img.png>
*********************** =In year 2024\n<img:images/img_1.png>;

**************[#gold]:Harun (Aaron)
** Brother of **Musa**;



* <img:images/img_2.png>
** <img:images/img_3.png>



* =Adam \n* Father of HumanKind
**:* Prhophet __means__ Rusool
* Rusool = Rusool & Nubee
* Nubee is not Rusool;


**:==Hazrat Ibrahim (Abraham)
* Had 2 sons
* Both were born when
  he was 80- years old
* He saw a dream in which
 he slaughter **Hazrat Ismail**
* Father of Monotheism;
***[#pink]:==Hazrat Ishaq or Isaac //**__(Israeli)__**//
* **Israeli:** are both christan & jews;
****[#yellow]:==Hazrat Musa (Moses)
* Prophet & Rasool
* Followers are called **(Israeli)**
* **Book-1:** Tourat
* Led to the exodus
** In Urdu, the word "exodus" can be translated as "ہجرت" or "Hijrat"
    in Roman Urdu script. It refers to a journey by a large group of
    people to escape from a hostile environment or any significant
    migration, often associated with the departure of the Israelites from
    Egypt under the leadership of Moses, an event known as "the Exodus"
    in history;

*****[#yellow]:==Hazrat Dauood
* Prophet & Rasool
* Followers are called **(Israeli)**
* **Book-2:** Zaboor
* **The Psalmist:** is a composer or writer, particularly
associated with the creation of biblical psalms, and the
Book of Psalms contains many of these religious
compositions. King David (Dauod) is one of the prominent
figures associated with the authorship of some of
these psalms.;

******[#yellow]:==Hazrat Esah
* Prophet & Rasool
* Followers are called **(Israeli)**
* **Book-3:** Injeel or Bible
* Born of the virgin Mary
** Maryam (Mary)
* **Hanged by Jews**;
***[#gold] ==Hazrat Ismail/Ishmael
****[#lime]:==Hazrat Muhammad
* Prophet & Rasool
* Followers are called **(Muhammadi)**
* **Book-4:** Quran Majeed
* Last Prophet;




* Forefathers of Hazrat Muhammad
** Banu Hashim Clan
*** Hashim
**** Abd al-Muttalib **(Grandfather)**
***** Abdulah **(Father)**
****** Prophet Muhammad (Peace Be Upon Him)

** Quraysh Tribe
*** Abd Manaf
**** **Hashim (as mentioned above)**
*** Abd Shams
*** Abd al-Dar
*** Abd Manaf (as mentioned above)

** Important Figures
*** Abdul-Muttalib **(Grandfather)**
*** Abdullah **(Father)**
*** Amina **(Mother)**
*** Abdul-Muttalib **(Paternal Grandfather)**
*** Abdul-Muttalib **(Maternal Grandfather)**


@endmindmap



@endmindmap
