

@startmindmap


title =  will add .vpp files here when I will create for some reasonable projects for reuse
*  will add .vpp files here when I will create for some reasonable projects for reuse

@endmindmap