@startmindmap
title =Data Cleaning
!theme hacker

* Data Cleaning
** Definition
*** Data cleaning is the process of identifying and rectifying errors, inconsistencies, and inaccuracies in data to improve its quality and reliability.

** Importance
*** **Ensures Data Quality:** High-quality data is vital for accurate analysis and decision-making.
*** **Enhances Credibility:** Clean data increases trust in reports and insights.
*** **Minimizes Errors:** Reduces the likelihood of errors in downstream processes.

** Data Cleaning Techniques
*** Handling Missing Values
****[#yellow] <i><size:14>**Imputation:** Replacing missing values with estimated values (mean, median, mode).
****[#yellow] <i><size:14>**Removal:** Eliminating rows or columns with excessive missing data.
****[#yellow] <i><size:14>**Interpolation:** Estimating missing values based on surrounding data points.

*** Outlier Detection and Treatment
****[#yellow] <i><size:14>Identifying outliers that significantly deviate from the norm.
****[#yellow] <i><size:14>Treatment methods may include removal, transformation, or imputation.

*** Data Deduplication
****[#yellow] <i><size:14>Detecting and removing duplicate records or observations.
****[#yellow] <i><size:14>Ensures data integrity and prevents double-counting.

*** Standardizing Data
****[#yellow] <i><size:14>Consistent formatting of data (e.g., date formats, capitalization).
****[#yellow] <i><size:14>Normalizing units and scales for uniformity.

** Data Cleaning Tools
*** OpenRefine
****[#yellow] <i><size:14>A powerful tool for data cleaning and transformation.

*** pandas (Python library)
****[#yellow] <i><size:14>Popular for data cleaning and manipulation in Python.

*** Excel
****[#yellow] <i><size:14>Basic data cleaning operations can be performed using Excel.

** Considerations
***[#black] <b><i><size:14>[[docs/AI-ML-DL-Data-Science-and-BigData/data-science/data-engineering/Data-Profiling.puml Data Profiling]]
****[#yellow] <i><size:14>Understanding the characteristics and distribution of data.

*** Data Validation
****[#yellow] <i><size:14>Implementing data validation checks to catch errors early.

*** Automation
****[#yellow] <i><size:14>Developing automated data cleaning processes for efficiency.

*** Documentation
****[#yellow] <i><size:14>Maintaining documentation of data cleaning steps for reproducibility.

** Best Practices
*** Data Auditing
****[#yellow] <i><size:14>Regularly audit and monitor data quality.

*** Version Control
****[#yellow] <i><size:14>Apply version control to data cleaning scripts and processes.

*** Data Backups
****[#yellow] <i><size:14>Make backups before performing extensive data cleaning.

*** Collaboration
****[#yellow] <i><size:14>Collaborate with domain experts and stakeholders to validate data changes.

@endmindmap
