@startmindmap
title = __ Political Science__

* Political Science
** Branches of Political Science
*** Comparative Politics
**** Political Culture
**** Regime Types
**** Electoral Systems
**** Public Opinion
*** International Relations
**** Diplomacy
**** Foreign Policy
**** International Organizations
**** Globalization
*** Political Theory
**** Political Philosophy
**** Political Ideologies
**** Political Systems
**** Democracy
**** Citizenship
*** Public Administration
**** Bureaucracy
**** Policy Analysis
**** Public Management
**** Public Finance
**[#yellow] **Key Concepts in Political Science**
***[#pink] **Power**
***[#pink] Authority
***[#pink] Legitimacy
***[#pink] Sovereignty
***[#pink] State
***[#pink] Government
***[#pink] Civil Society
***[#pink] Rights
***[#pink] Liberty
***[#pink] Equality
***[#pink] Justice
***[#pink] Democracy
@endmindmap
