= Principles for Dealing with the Changing World Order by Ray Dalio

I believe the world is changing in big ways that haven’t happened before in our lifetimes but have many times in history, so I knew I needed to study past changes to understand what is happening now and help me to anticipate what is likely to happen.

I shared what I learned in my book, Principles for Dealing with the Changing World Order, and my hope is that this animation gives people an easy way to understand the key ideas from the book in a simple and entertaining way. In the first 18 minutes, you’ll get the gist of what drives the “Big Cycle” of rise and decline of nations through time and where we now are in that cycle. If you give me 20 minutes more to watch the whole thing, and I will show you how the big cycle worked across the last *500 years of history—and what the current world leading power, the United States, needs to do to remain strong.*



Key Sections:
1:33 - How I Learned to Anticipate the Future by Studying the Past
8:00 - Changing Orders
11:38 - The Big Cycle
18:26 - 500 Years of Big Cycles
18:45 - The Rise
26:16 - The Top
32:01- The Decline
39:39 - The Future

.Principles for Dealing with the Changing World Order by Ray Dalio
+++
<iframe width="560" height="315" src="https://www.youtube.com/embed/xguam0TKMw8?si=1k9jN2crd8qXaZUf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
+++
