:numbered:
:hardbreaks:
:sectnumlevels: 6
:sectids:
:sectanchors:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

== Introduction
=== Purpose

Delineate the purpose of the software to be specified.



=== Scope

.Describe the scope of the software under consideration by 
.. Identifying the software product(s) to be produced by name (e.g., Host DBMS, Report Generator, etc.); 
.. Explaining what the software product(s) will do; 
.. Describing the application of the software being specified, including relevant benefits, objectives, and goals; 
.. Being consistent with similar statements in higher-level specifications (e.g., the system requirements specification), if they exist. 

=== Product overview
==== Product perspective

Define the system's relationship to other related products. 

If the product is an element of a larger system, then relate the requirements of that larger system to the functionality of the product covered by the SRS. 

If the product is an element of a larger system, then identify the interfaces between the product covered by the SRS and the larger system of which the product is an element. 

A block diagram showing the major elements of the larger system, interconnections, and external interfaces can be helpful. 

.Describe how the software operates within the following constraints: 
.. System interfaces; 
.. User interfaces; 
.. Hardware interfaces; 
.. Software interfaces; 
.. Communications interfaces; 
.. Memory; 
.. Operations; 
.. Site adaptation requirements. 

===== System interfaces

List each system interface and identify the functionality of the software to accomplish the system requirement and the interface description to match the system. 

===== User interfaces 

.Specify the following: 
.. The logical characteristics of each interface between the software product and its users. This includes those configuration characteristics (e.g., required screen formats, page or window layouts, content of any reports or menus, or availability of programmable function keys) necessary to accomplish the software requirements. 
.. All the aspects of optimizing the interface with the person who uses, maintains, or provides other support to the system. This may simply comprise a list of do's and don'ts on how the system will appear to the user. One example may be a requirement for the option of long or short error messages. This may also be specified in the Software System Attributes under a section titled Ease of Use. 

[NOTE]
A style guide for the user interface can provide consistent rules for organization, coding, and interaction of the user with the system. 

===== Hardware interfaces 

Specify the logical characteristics of each interface between the software product and the hardware elements of the system. This includes configuration characteristics (number of ports, instruction sets, etc.). It also covers such matters as what devices are to be supported, how they are to be supported, and protocols. For example, terminal support may specify full-screen support as opposed to line-by-line support. 

===== Software interfaces 

Specify the use of other required software products (e.g., a data management system, an operating system, or a mathematical package), and interfaces with other application systems (e.g., the linkage between an accounts receivable system and a general ledger system). 

.For each required software product, specify: 
.. Name; 
.. Mnemonic; 
.. Specification number; 
.. Version number; 
.. Source. 

.For each interface specify: 
.. Discussion of the purpose of the interfacing software as related to this software product. 
.. Definition of the interface in terms of message content and format. It is not necessary to detail any welldocumented interface, but a reference to the document defining the interface is required. 

===== Communications interfaces 

Specify the various interfaces to communications such as local network protocols. 

===== Memory constraints 

Specify any applicable characteristics and limits on primary and secondary memory. 

===== Operations 

.Specify the normal and special operations required by the user such as
.. The various modes of operations in the user organization (e.g., user-initiated operations); 
.. Periods of interactive operations and periods of unattended operations; 
.. Data processing support functions; 
.. Backup and recovery operations. 

[NOTE]
This is sometimes specified as part of the User Interfaces section. 

===== Site adaptation requirements 

.The site adaptation requirements include 
.. Definition of the requirements for any data or initialization sequences that are specific to a given site, mission, or operational mode (e.g., grid values, safety limits, etc.); 
.. Specification of the site or mission-related features that should be modified to adapt the software to a particular installation. 

==== Product functions

Provide a summary of the major functions that the software will perform. For example, an SRS for an accounting program may use this part to address customer account maintenance, customer statement, and invoice preparation without mentioning the vast amount of detail that each of those functions requires. 

Sometimes the function summary that is necessary for this part can be taken directly from the section of the higher-level specification (if one exists) that allocates particular functions to the software product. 

.Note that for the sake of clarity 
.. The product functions should be organized in a way that makes the list of functions understandable to the acquirer or to anyone else reading the document for the first time. 
.. Textual or graphical methods can be used to show the different functions and their relationships. Such a diagram is not intended to show a design of a product, but simply shows the logical relationships among variables. 

==== User characteristics

Describe those general characteristics of the intended groups of users of the product including characteristics that may influence usability, such as educational level, experience, disabilities, and technical expertise. This description should not state specific requirements, but rather should state the reasons why certain specific requirements are later specified in specific requirements in subclause <<SpecificRequirements.adoc#truespecific-requirements>>. 

[NOTE] 
Where appropriate, the user characteristics of the SyRS and SRS should be consistent. 

==== Limitations

.Provide a general description of any other items that will limit the supplier's options, including 
.. Regulatory policies; 
.. Hardware limitations (e.g., signal timing requirements); 
.. Interfaces to other applications; 
.. Parallel operation; 
.. Audit functions; 
.. Control functions; 
.. Higher-order language requirements; 
.. Signal handshake protocols (e.g., XON-XOFF, ACK-NACK); 
.. Quality requirements (e.g., reliability) 
.. Criticality of the application; 
.. Safety and security considerations. 
.. Physical/mental considerations

=== Definitions

Provide definitions for any words or phrases that have special meaning beyond normal dictionary definitions. 