:numbered:
:hardbreaks:
:sectnumlevels: 6
:sectids:
:sectanchors:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

== Specific requirements

Specify all of the software requirements to a level of detail sufficient to enable designers to design a software system to satisfy those requirements. 

Specify all of the software requirements to a level of detail sufficient to enable testers to test that the software system satisfies those requirements. 

At a minimum, describe every input (stimulus) into the software system, every output (response) from the software system, and all functions performed by the software system in response to an input or in support of an output. 

.The specific requirements should: 
.. Be stated in conformance with all the characteristics described in subclause 5.2 of this International Standard. 
.. Be cross-referenced to earlier documents that relate. 
.. Be uniquely identifiable.

=== External interfaces

Define all inputs into and outputs from the software system. The description should complement the interface descriptions in <<Introduction.adoc#truesystem-interfaces>> through <<Introduction.adoc#truecommunications-interfaces>>, and should not repeat information there. 

.Each interface defined should include the following content: 
.. Name of item; 
.. Description of purpose; 
.. Source of input or destination of output; 
.. Valid range, accuracy, and/or tolerance; 
.. Units of measure; 
.. Timing; 
.. Relationships to other inputs/outputs; 
.. Screen formats/organization; 
.. Window formats/organization; 
.. Data formats; 
.. Command formats; 
.. Endmessages.

=== Functions

.Define the fundamental actions that have to take place in the software in accepting and processing the inputs and in processing and generating the outputs, including 
.. Validity checks on the inputs 
.. Exact sequence of operations 
.. Responses to abnormal situations, including 
... Overflow 
... Communication facilities 
... Error handling and recovery 
.. Effect of parameters 
.. Relationship of outputs to inputs, including 
... Input/output sequences 
... Formulas for input to output conversion 

It may be appropriate to partition the functional requirements into subfunctions or subprocesses. This does not imply that the software design will also be partitioned that way. 

=== Usability requirements

Define usability (quality in use) requirements. Usability requirements and objectives for the software system include measurable effectiveness, efficiency, and satisfaction criteria in specific contexts of use. 

=== Performance requirements

Specify both the static and the dynamic numerical requirements placed on the software or on human interaction with the software as a whole. 

.Static numerical requirements may include the following:
.. The number of terminals to be supported; 
.. The number of simultaneous users to be supported; 
.. Amount and type of information to be handled. 

Static numerical requirements are sometimes identified under a separate section entitled Capacity. 

Dynamic numerical requirements may include, for example, the numbers of transactions and tasks and the amount of data to be processed within certain time periods for both normal and peak workload conditions. 

The performance requirements should be stated in measurable terms. 

For example, 
====
95 % of the transactions shall be processed in less than 1 second. 
====

rather than, 
====
An operator shall not have to wait for the transaction to complete.
====

[NOTE]
Numerical limits applied to one specific function are normally specified as part of the processing subparagraph description of that function. 

=== Logical database requirements

.Specify the logical requirements for any information that is to be placed into a database, including: 
.. Types of information used by various functions; 
.. Frequency of use; 
.. Accessing capabilities; 
.. Data entities and their relationships; 
.. Integrity constraints; 
.. Data retention requirements. 

=== Design constraints

Specify constraints on the system design imposed by external standards, regulatory requirements, or project limitations. 

=== Standards compliance 

.Specify the requirements derived from existing standards or regulations, including: 
.. Report format; 
.. Data naming; 
.. Accounting procedures; 
.. Audit tracing. 

For example, this could specify the requirement for software to trace processing activity. Such traces are needed for some applications to meet minimum regulatory or financial standards. An audit trace requirement may, for example, state that all changes to a payroll database shall be recorded in a trace file with before and after values. 

=== Software system attributes

.Specify the required attributes of the software product. The following is a partial list of examples: 
.. Reliability - Specify the factors required to establish the required reliability of the software system at time of delivery. 
.. Availability - Specify the factors required to guarantee a defined availability level for the entire system such as checkpoint, recovery, and restart. 
.. Security - Specify the requirements to protect the software from accidental or malicious access, use modification, destruction, or disclosure. Specific requirements in this area could include the need to: 
... Utilize certain cryptographic techniques; 
... Keep specific log or history data sets; 
... Assign certain functions to different modules; 
... Restrict communications between some areas of the program; 
... Check data integrity for critical variables; 
... Assure data privacy. 
.. Maintainability - Specify attributes of software that relate to the ease of maintenance of the software itself. These may include requirements for certain modularity, interfaces, or complexity limitation. Requirements should not be placed here just because they are thought to be good design practices. 
.. Portability - Specify attributes of software that relate to the ease of porting the software to other host machines and/or operating systems, including: 
... Percentage of elements with host-dependent code; 
... Percentage of code that is host dependent; 
... Use of a proven portable language; 
... Use of a particular compiler or language subset; 
... Use of a particular operating system. 

=== Supporting information

.The SRS should contain additional supporting information including 
.. Sample input/output formats, descriptions of cost analysis studies, or results of user surveys; 
.. Supporting or background information that can help the readers of the SRS; 
.. A description of the problems to be solved by the software; 
.. Special packaging instructions for the code and the media to meet security, export, initial loading, or other requirements. 

The SRS should explicitly state whether or not these information items are to be considered part of the requirements.  
