@startmindmap
title =__ Conditionals__

* Conditionals
** Zero Conditional
*** Form
**** If + present simple, present simple
*** Use
**** To talk about things that are always true
**** To talk about cause and effect
**** To give instructions or directions
**** To make general statements
** First Conditional
*** Form
**** If + present simple, will + base form of the verb
**** If + present simple, can/could/may/might + base form of the verb
**** If + present simple, imperative
*** Use
**** To talk about possible future situations
**** To make offers, suggestions, and requests
**** To talk about real situations
** Second Conditional
*** Form
**** If + past simple, would + base form of the verb
**** If + past simple, could/might + base form of the verb
*** Use
**** To talk about hypothetical or imaginary situations in the present or future
**** To make suggestions or give advice
**** To talk about unlikely or impossible situations in the present or future
** Third Conditional
*** Form
**** If + past perfect, would have + past participle
**** If + past perfect, could/might have + past participle
*** Use
**** To talk about hypothetical or imaginary situations in the past
**** To talk about regrets or something that did not happen in the past
**** To criticize or speculate about past actions
** Mixed Conditional
*** Form
**** If + past perfect, would + base form of the verb
**** If + past perfect, could/might + base form of the verb
*** Use
**** To talk about hypothetical or imaginary situations in the present that have a connection to the past
**** To talk about regrets or something that did not happen in the past that has a connection to the present
**** To talk about past actions that have a connection to the present
@endmindmap
