@startmindmap
* Converting Active Voice to Passive Voice
** Identify the Subject and Object
*** Subject - the person, thing, or entity performing the action
*** Object - the person, thing, or entity on which the action is being performed
** Change the Object to the Subject
*** The object becomes the subject in the passive voice
** Add the Auxiliary Verb 'to be'
*** The auxiliary verb 'to be' (is, am, are, was, were, be, been, being) is added according to the tense
** Change the Verb Form
*** The main verb is changed to its past participle form
** Add the Preposition 'by'
*** The preposition 'by' is added to show the performer of the action in the passive voice
** Add any Necessary Words
*** Sometimes additional words are needed to make the sentence grammatically correct
** Examples
*** Active: The cat chased the mouse.
*** Passive: The mouse was chased by the cat.
@endmindmap
