@startmindmap
title =__ English Grammar Cheatsheet__

* English Grammar Cheatsheet
** Parts of Speech
*** Nouns
**** Common Nouns
**** Proper Nouns
**** Concrete Nouns
**** Abstract Nouns
*** Pronouns
**** Personal Pronouns
**** Possessive Pronouns
**** Reflexive Pronouns
**** Demonstrative Pronouns
**** Interrogative Pronouns
**** Relative Pronouns
*** Verbs
**** Action Verbs
**** Linking Verbs
**** Helping Verbs
*** Adjectives
*** Adverbs
*** Prepositions
*** Conjunctions
*** Interjections
** Tenses
*** Simple Present
*** Present Continuous
*** Simple Past
*** Past Continuous
*** Present Perfect
*** Past Perfect
*** Future Simple
*** Future Continuous
*** Future Perfect
** Sentence Structure
*** Subject-Verb Agreement
*** Types of Sentences
**** Simple Sentence
**** Compound Sentence
**** Complex Sentence
**** Compound-Complex Sentence
*** Parts of a Sentence
**** Subject
**** Verb
**** Object
**** Complement
** Punctuation
*** Period
*** Question Mark
*** Exclamation Mark
*** Comma
*** Semicolon
*** Colon
*** Apostrophe
*** Quotation Marks
*** Parentheses
*** Brackets
*** Hyphen
*** Dash
*** Ellipsis
** Common Errors
*** Homophones
*** Subject-Verb Disagreement
*** Misplaced Modifiers
*** Apostrophe Errors
*** Run-On Sentences
*** Comma Splices
@endmindmap
