@startmindmap
title =__ Modals__

* Modals
** Definition
*** Auxiliary verbs used to express various meanings
** Can / Could
*** Ability
*** Possibility / Permission
*** Polite Request / Offer
*** Suggestion
** May / Might
*** Possibility
*** Permission / Request
*** Probability
** Will / Would
*** Future Action / Prediction
*** Habitual Action in the Past
*** Polite Request
*** Preference
** Shall / Should
*** Obligation
*** Suggestion
*** Future Time
** Must / Have To
*** Necessity
*** Obligation
*** Prohibition
** Need / Needn't
*** Necessity / Lack of Necessity
** Ought To / Had Better
*** Advice / Suggestion
** Used To / Would
*** Past Habit
@endmindmap
