@startmindmap
title =__ Syntax__

* Syntax
** Parts of Speech
*** Noun
**** Common Noun
**** Proper Noun
**** Abstract Noun
**** Concrete Noun
*** Pronoun
**** Personal Pronoun
**** Possessive Pronoun
**** Reflexive Pronoun
**** Demonstrative Pronoun
**** Interrogative Pronoun
**** Relative Pronoun
**** Indefinite Pronoun
*** Verb
**** Action Verb
**** Linking Verb
**** Helping Verb
*** Adjective
**** Descriptive Adjective
**** Limiting Adjective
*** Adverb
**** Manner Adverb
**** Place Adverb
**** Time Adverb
**** Degree Adverb
*** Preposition
**** Simple Preposition
**** Compound Preposition
*** Conjunction
**** Coordinating Conjunction
**** Subordinating Conjunction
**** Correlative Conjunction
*** Interjection
**** Strong Interjection
**** Mild Interjection
** Phrases
*** Noun Phrase
*** Verb Phrase
*** Adjective Phrase
*** Adverbial Phrase
*** Prepositional Phrase
*** Gerund Phrase
*** Infinitive Phrase
*** Participial Phrase
*** Absolute Phrase
** Clauses
*** Independent Clause
*** Dependent Clause
**** Adverb Clause
**** Noun Clause
**** Adjective Clause
** Sentence Types
*** Simple Sentence
*** Compound Sentence
*** Complex Sentence
*** Compound-Complex Sentence
@endmindmap
