@startmindmap

*:*It's also worth noting that __new techniques and methodologies are being developed all the time,__ and what is considered best practice can change over time. So, it's important to keep up to date with the latest developments in the field.
* **It's also worth noting that depending on the specific needs and goals of the organization and the stakeholders involved, different techniques may be more or less appropriate.**
   It's important to evaluate the suitability of each technique for a particular situation before using it.;


title = __choosing the right technique or framework based on the specific problem and context:__

* Choosing the Right \nTechnique/Framework

** Define the Problem
*** Understand the Problem Space
**** Identify the Business Need
**** Analyze the Requirements
*** Determine the Data
**** Size of the Data
**** Complexity of the Data
****[#pink] **Structure of the Data**
***** Structured-data or labeled data (15%-20%) on internet
***** un-Structured-data or un-labeled data (80%-85%) on internet

** Evaluate Techniques/Frameworks
*** Machine Learning
**** <color #green>**Supervised Learning**</color> (works on **labeled data**), \nlabeled data is also called as **structured data**
***** Regression
***** Classification
**** <color #green>**Unsupervised Learning**</color> (works on **un-labeled data**), \nunlabeled data is also called as **un-structured data**
***** Clustering
***** Dimensionality Reduction
***** Anomaly detection
**** Reinforcement Learning
***** agent, reward & punishment, state, environment and action
**** Deep Learning
***** Convolutional Neural Networks (CNN)
***** Recurrent Neural Networks (RNN)
*** Statistical Models
**** Linear Regression
**** Logistic Regression
**** Time Series Analysis
**** Bayesian Inference
*** Optimization Methods
**** Gradient Descent
**** Evolutionary Algorithms
**** Simulated Annealing
**** Genetic Algorithms
*** Rule-Based Systems
**** Decision Trees
**** Random Forest
**** Association Rules
**** Fuzzy Logic
*** Other Techniques/Frameworks
**** Natural Language Processing
**** Computer Vision
**** Graph Theory

** Consider the Context
*** Resource Constraints
**** Compute Resources
**** Memory Resources
**** Storage Resources
*** Time Constraints
**** Real-Time Applications
**** Batch Processing
**** Offline Processing
*** Organizational Constraints
**** Skillset of Team
**** Existing Infrastructure
**** Budget Constraints

@endmindmap
