@startmindmap
title =__ Data Pipeline__

* **[[https://youtu.be/VtzvF17ysbc  ]]**
* **[[https://hazelcast.com/glossary/data-pipeline/]]**

* Data Pipeline
** Data Source
*** File Systems
**** Local File System
**** Distributed File System
*** Relational Databases
**** MySQL
**** Oracle
**** SQL Server
**** PostgreSQL
*** NoSQL Databases
**** MongoDB
**** Cassandra
**** Redis
**** Elasticsearch
** Data Ingestion (ETL)
*** Data **Extraction**
**** File Parsing
**** API Integration
**** Database Queries
*** Data **Transformation**
**** Data Cleaning
**** Data Validation
**** Data Enrichment
**** Data Formatting
*** Data **Loading**
**** Batch Loading
**** Real-time Streaming
**** Database Insertion
**** File Writing
** Data Processing
*** Data Manipulation
**** Filtering
**** Aggregation
**** Joining
**** Sorting
*** Data Analysis
**** Descriptive Statistics
**** Data Mining
**** Machine Learning
**** Predictive Modeling
*** Data Visualization
**** Charts
**** Graphs
**** Dashboards
**** Reports
** Data Storage
*** Data Warehouses
**** On-Premise Data Warehouses
**** Cloud Data Warehouses
*** Data Lakes
**** Hadoop Distributed File System (HDFS)
**** Amazon S3
**** Google Cloud Storage
**** Azure Blob Storage
*** NoSQL Databases
**** MongoDB
**** Cassandra
**** Redis
**** Elasticsearch
** Data Delivery
*** Data APIs
**** RESTful APIs
**** GraphQL APIs
**** SOAP APIs
*** Data Streaming
**** Apache Kafka
**** Amazon Kinesis
**** Apache Flink
**** Apache Spark Streaming
*** Data Export
**** File Formats (CSV, JSON, XML)
**** Database Replication
**** API Integration
**** Data Publishing
@endmindmap
