@startmindmap
skinparam nodeWidth 250
skinparam nodeHeight 40
skinparam nodeFontSize 14
skinparam ArrowColor #808080

title =__ Criminal Law__

* Criminal Law
** Pakistan Penal Code (PPC)
*** Offenses Against the Human Body
**** Murder
**** Manslaughter
**** Assault and Battery
**** Rape and Sexual Assault
*** Offenses Against Property
**** Theft
**** Robbery
**** Burglary
**** Fraud
*** Offenses Against Public Tranquility سکون
**** Rioting
**** Unlawful Assembly
**** Breach of Peace
**** Public Nuisance
*** Offenses Against the State
**** Sedition بغاوت
**** Treason غداری
**** Espionage جاسوسی
**** Terrorism
*** Offenses Against the Administration of Justice
**** Contempt حقارت of Court
**** Perjury جھوٹی گواہی
**** Obstruction رکاوٹ of Justice
**** Bribery رشوت
** Criminal Procedure Code (CrPC)
*** Investigation Process
**** Registration of FIR
**** Gathering Evidence
**** Arrest and Detention نظر بندی
**** Interrogation and Confessions
*** Arrest and Bail ضمانت
**** Grounds for Arrest
**** Procedure for Arrest
**** Bail Application and Hearing
**** Types of Bail
*** Trial (test or آزمائش ) and Sentencing سزا سنانا
**** Charges and Framing of Charges
**** Examination of Witnesses
**** Cross-Examination and Re-Examination
**** Arguments and Final Statements
**** Pronouncement of Judgment
*** Appeals and Revision
**** Appellate Courts
**** Grounds for Appeal
**** Filing of Appeal
**** Revisionary Jurisdiction عملداری
@endmindmap
