@startmindmap
skinparam nodeWidth 250
skinparam nodeHeight 40
skinparam nodeFontSize 14
skinparam ArrowColor #808080

title =__ Pakistan Legislation__

* Pakistan Legislation قانون سازی
** Constitution
*** Fundamental Rights
**** Right to Life
**** Right to Freedom of Speech
**** Right to Equality
**** Right to Education
*** Parliament
**** National Assembly
**** Senate
**** Legislation قانون سازی Process
***** Introduction of Bill
***** Committee Review
***** Debate and Voting
***** President's Approval
**** Legislation Types
***** Constitutional Amendments (change)
***** Ordinary Laws
***** Money Bills
** Criminal Law
*** Pakistan Penal (سزا کے متعلق) Code (PPC)
**** Offenses Against the Human Body
**** Offenses Against Property
**** Offenses Against Public Tranquility (peace or سکون)
**** Offenses Against the State
**** Offenses Against the Administration of Justice
*** Criminal Procedure Code (CrPC)
**** Investigation Process
**** Arrest and Bail
**** Trial and Sentencing
**** Appeals and Revision
** Civil Law
*** Civil Procedure Code (CPC)
**** Jurisdiction of Courts
**** Pleadings and Written Statements
**** Evidence and Witnesses
**** Judgments and Decrees فرمان
**** Execution of Decrees
*** Family Laws
**** Marriage and Divorce
**** Inheritance and Succession
**** Child Custody and Guardianship
**** Dowry and Domestic Violence
** Business and Commercial Law
*** Companies Act
**** Incorporation and Registration
**** Shareholding and Shareholders' Rights
**** Directors and Board of Directors
**** Mergers and Acquisitions
*** Contracts Law
**** Formation of Contracts
**** Terms and Conditions
**** Breach خلاف ورزی of Contract (promise)
**** Remedies and Damages
** Intellectual Property Law
*** Copyright Law
**** Protection of Literary and Artistic Works
**** Ownership and Licensing
**** Infringement (deviation خلاف ورزی) and Enforcement
*** Trademark Law
**** Registration and Protection of Trademarks
**** Use and Authorization
**** Trademark Infringement
**** Passing Off
*** Patent (copyright) Law
**** Patentability and Inventive Step
**** Application and Examination
**** Grant and Term
**** Infringement and Invalidity
@endmindmap
