@startmindmap
title =__ Politics in Pakistan__

* Overview
** Political System
*** Federal Government
**** President
**** Prime Minister
**** Cabinet
**** Parliament
**** Senate
**** National Assembly
**** Council of Islamic Ideology
**** Council of Common Interests
*** Provincial Governments
**** Chief Minister
**** Cabinet
**** Provincial Assembly
*** Local Governments
**** Mayor
**** Municipal Corporation
**** Union Council
** Political Parties
*** Pakistan Tehreek-e-Insaf (PTI)
*** Pakistan Muslim League-Nawaz (PML-N)
*** Pakistan People's Party (PPP)
*** Jamiat Ulema-e-Islam-Fazl (JUI-F)
*** Muttahida Qaumi Movement-Pakistan (MQM-P)
*** Awami National Party (ANP)
*** Balochistan National Party-Mengal (BNP-M)
*** Jamaat-e-Islami (JI)
*** Pakistan Awami Tehreek (PAT)
*** Pak Sarzameen Party (PSP)
** Election Process
*** Election Commission of Pakistan
*** Voter Registration
*** Political Campaigning
*** Polling Day
*** Vote Counting
** Political Issues
*** Corruption
*** Terrorism
*** Sectarianism
*** Poverty
*** Education
*** Health
*** Infrastructure
*** Water Crisis
*** Energy Crisis
@endmindmap
