Lean Canvas
===========
Syaiful Nizam Yahya <syaifulnizamyahya@gmail.com>
v1.0, 2016-02-09
:website: http://syaifulnizamyahya.bitbucket.org/

What is Lean Canvas? +
https://canvanizer.com/new/lean-canvas

Why Lean Canvas? +
https://leanstack.com/why-lean-canvas/

Alternative Lean Canvas tool +
https://app.leanstack.com/ +
https://canvanizer.com/new/lean-canvas

[width="100%",options=""]
[cols="2a,2a,1a,1a,2a,2a"]
:!toc:
|====================
.2+|

*PROBLEM* +
List your customer's top 3 problems

*EXISTING ALTERNATIVES* +
List how these problems are solved today

| 

*SOLUTION* +
Outline a possible solution for each problem

2.2+| 

*UNIQUE VALUE PROPOSITION* +
Single, clear, compelling message that turns an unaware visitors into an interested prospect

*HIGH LEVEL CONCEPT* +
List your X for Y analogy (e.g. YouTube = Flickr for videos)

| 

*UNFAIR ADVANTAGE* +
Something that can't be easily copied or bought

.2+| 

*CUSTOMER SEGMENTS* +
List your target customers and users

*EARLY ADOPTERS* +
List the characteristics of your ideal customers

| 

*KEY METRICS* +
List the key numbers that tell you how your business is doing

| 

*CHANNELS* +
List your path to customers

3.+| 

*COST STRUCTURE* +
List your fixed and variable costs

3.+| 

*REVENUE STREAMS* +
List your sources of revenue

|====================
