:numbered:
:hardbreaks:
:sectnumlevels: 6
:sectids:
:sectanchors:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

== Specific requirements (organized by response)

Some systems can be best organized by describing all the functions in support of the generation of a response. For example, the functions of a personnel system may be organized into sections corresponding to all functions associated with generating paychecks, all functions associated with generating a current list of employees, etc. 

There are many notations, methods, and automated support tools available to aid in the documentation of requirements. For the most part, their usefulness is a function of organization. For example, when organizing by mode, finite state machines or state charts may prove helpful; when organizing by object, object-oriented analysis may prove helpful; when organizing by feature, stimulus-response sequences may prove helpful; and when organizing by functional hierarchy, data flow diagrams and data dictionaries may prove helpful.

This section of the SRS should contain all of the software requirements to a level of detail sufficient to enable designers to design a system to satisfy those requirements, and testers to test that the system satisfies those requirements. Throughout this section, every stated requirement should be externally perceivable by users, operators, or other external systems. These requirements should include at a minimum a description of every input (stimulus) into the system, every output (response) from the system, and all functions performed by the system in response to an input or in support of an output.

.As this is often the largest and most important part of the SRS, the following principles apply:
.. Specific requirements should be stated in conformance with all the characteristics of a good SRS.
An SRS should be
... Correct;
... Unambiguous; 
... Complete; 
... Consistent; 
... Ranked for importance and/or stability; 
... Verifiable; 
... Modifiable; 
... Traceable. 

.. Specific requirements should be cross-referenced to earlier documents that relate.
.. All requirements should be uniquely identifiable.
.. Careful attention should be given to organizing the requirements to maximize readability.

=== External interface requirements

This should be a detailed description of all inputs into and outputs from the software system. It should complement the interface descriptions in <<OverallDescription.adoc#trueoverall-description,Overall Description>> and should not repeat information there.

.It should include both content and format as follows:
.. Name of item;
.. Description of purpose;
.. Source of input or destination of output;
.. Valid range, accuracy, and/or tolerance;
.. Units of measure;
.. Timing;
.. Relationships to other inputs/outputs;
.. Screen formats/organization;
.. Window formats/organization;
.. Data formats;
.. Command formats;
.. End messages.

==== User interfaces
==== Hardware interfaces
==== Software interfaces
==== Communications interfaces
=== Functional requirements

Functional requirements should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. These are generally listed as "shall" statements starting with "The system shall..."

.These include
.. Validity checks on the inputs
.. Exact sequence of operations
.. Responses to abnormal situations, including
... Overflow
... Communication facilities
... Error handling and recovery
.. Effect of parameters
.. Relationship of outputs to inputs, including
... Input/output sequences
... Formulas for input to output conversion

It may be appropriate to partition the functional requirements into subfunctions or subprocesses. This does not imply that the software design will also be partitioned that way.

This section may be described in native language (e.g., English), in pseudocode, in a system denition language, or in four subsections titled: Introduction, Inputs, Processing, and Outputs. 

==== Response 1
===== Functional requirement 1
===== Functional requirement 2
===== Functional requirement 3
==== Response 2
===== Functional requirement 1
===== Functional requirement 2
===== Functional requirement 3
==== Response 3
===== Functional requirement 1
===== Functional requirement 2
===== Functional requirement 3

=== Performance requirements

This subsection should specify both the static and the dynamic numerical requirements placed on the software or on human interaction with the software as a whole.

.Static numerical requirements may include the following:
.. The number of terminals to be supported;
.. The number of simultaneous users to be supported;
.. Amount and type of information to be handled.

Static numerical requirements are sometimes identified under a separate section entitled Capacity.

Dynamic numerical requirements may include, for example, the numbers of transactions and tasks and the amount of data to be processed within certain time periods for both normal and peak workload conditions.

All of these requirements should be stated in measurable terms.

For example,
====
_95% of the transactions shall be processed in less than 1 s._
====

rather than,
====
_An operator shall not have to wait for the transaction to complete._
====

[NOTE]
Numerical limits applied to one specific function are normally specified as part of the processing subparagraph description of that function.

=== Logical database requirements

This should specify the logical requirements for any information that is to be placed into a database.

.This may include the following:
.. Types of information used by various functions;
.. Frequency of use;
.. Accessing capabilities;
.. Data entities and their relationships;
.. Integrity constraints;
.. Data retention requirements.

=== Design constraints

This should specify design constraints that can be imposed by other standards, hardware limitations, etc.

==== Standards compliance

This subsection should specify the requirements derived from existing standards or regulations.

.They may include the following:
.. Report format;
.. Data naming;
.. Accounting procedures;
.. Audit tracing.

For example, this could specify the requirement for software to trace processing activity. Such traces are needed for some applications to meet minimum regulatory or financial standards. An audit trace requirement may, for example, state that all changes to a payroll database must be recorded in a trace le with before and after values.

=== Software systems attributes

There are a number of attributes of software that can serve as requirements. It is important that required attributes be specified so that their achievement can be objectively verified. 

==== Reliability

This should specify the factors required to establish the required reliability of the software system at time of delivery.

====  Availability

This should specify the factors required to guarantee a defined availability level for the entire system such as checkpoint, recovery, and restart.

==== Security

This should specify the factors that protect the software from accidental or malicious access, use, modification, destruction, or disclosure.

.Specic requirements in this area could include the need to
.. Utilize certain cryptographical techniques; 
.. Keep specific log or history data sets;
.. Assign certain functions to different modules;
.. Restrict communications between some areas of the program;
.. Check data integrity for critical variables.

==== Maintainability

This should specify attributes of software that relate to the ease of maintenance of the software itself. There may be some requirement for certain modularity, interfaces, complexity, etc. Requirements should not be placed here just because they are thought to be good design practices.

==== Portability

This should specify attributes of software that relate to the ease of porting the software to other host machines and/or operating systems.

.This may include the following:
.. Percentage of components with host-dependent code;
.. Percentage of code that is host dependent;
.. Use of a proven portable language;
.. Use of a particular compiler or language subset;
.. Use of a particular operating system.

=== Other requirements

Other requirements can be inferred by running experiments with the prototype.

