@startmindmap
title =<i>Simple .Jar vs Modular .Jar
* <b><i>[[docs/3-programming-languages/JVM-ecosystem/java/java-9-onwards.puml java-9-onwards]] Modular .Jar, click me
*:<img:images/img_12.png>
<img:images/img_13.png>;
@endmindmap
