@startmindmap

title =__DevOps__
!theme hacker

* Principles
** Agile
** Continuous Delivery
** Automation
** Collaboration
** Monitoring
** Measurement
** Feedback
** Continuous Improvement
** Infrastructure as Code
** Microservices
**[#pink] ====Containers
* Culture
** Collaboration
** Shared Responsibility
** Transparency
** Continuous Learning
** Innovation
** Experimentation
** Blameless Culture
* Methods
** Scrum
** Kanban
** Lean
** ITIL
** Site Reliability Engineering (SRE)
** Value Stream Mapping
** DevSecOps



' Advanced DevOps

* Culture
** Agile Methodologies
** Continuous Improvement
** Collaboration
** Automation
** Learning Culture
** Ownership
* Processes
** Agile Frameworks
***[#yellow] ====<size:14>Scrum
***[#yellow] ====<size:14>Kanban
** Continuous Integration
** Continuous Delivery
** Continuous Deployment
** Release Management
** Change Management
** DevOps Metrics
* Tools
** Source Control
***[#yellow] ====<size:14>Git
***[#yellow] ====<size:14>GitHub
***[#yellow] ====<size:14>GitLab
***[#yellow] ====<size:14>Subversion
***[#yellow] ====<size:14>Mercurial
** Build Tools
***[#yellow] ====<size:14>Jenkins
***[#yellow] ====<size:14>Travis CI
***[#yellow] ====<size:14>CircleCI
***[#yellow] ====<size:14>GitLab CI/CD
** Configuration Management
***[#yellow] ====<size:14>Chef
***[#yellow] ====<size:14>Puppet
***[#yellow] ====<size:14>Ansible
***[#yellow] ====<size:14>SaltStack
**[#pink] ====Containers
***[#yellow] ====<size:14>Docker
***[#yellow] ====<size:14>Kubernetes
**[#gold] ====Cloud Computing
***[#yellow] ====<size:14>AWS
***[#yellow] ====<size:14>Azure
***[#yellow] ====<size:14>Google Cloud Platform
***[#yellow] ====<size:14>IBM Cloud
***[#yellow] ====<size:14>Oracle Cloud
** Monitoring and Logging
***[#yellow] ====<size:14>Prometheus
***[#yellow] ====<size:14>Grafana
***[#yellow] ====<size:14>Elasticsearch
***[#yellow] ====<size:14>Logstash
***[#yellow] ====<size:14>Kibana
***[#yellow] ====<size:14>ELK Stack

** Collaboration
***[#yellow] ====<size:14>Slack
***[#yellow] ====<size:14>Microsoft Teams
***[#yellow] ====<size:14>Jira
***[#yellow] ====<size:14>Confluence
* Skills
** Scripting Languages
***[#yellow] ====<size:14>Bash
***[#pink] ====<size:14>**Python**
***[#yellow] ====<size:14>Ruby
***[#yellow] ====<size:14>PowerShell
** Infrastructure as Code
***[#yellow] ====<size:14>Terraform
***[#yellow] ====<size:14>Pulumi
***[#yellow] ====<size:14>CloudFormation
** Continuous Integration/Delivery/Deployment
***[#yellow] ====<size:14>Jenkins
***[#yellow] ====<size:14>CircleCI
***[#yellow] ====<size:14>Travis CI
***[#yellow] ====<size:14>GitLab CI/CD
**[#lime] ====Container Orchestration
***[#yellow] ====<size:14>Kubernetes
***[#yellow] ====<size:14>Amazon ECS
***[#yellow] ====<size:14>Google Kubernetes Engine
***[#yellow] ====<size:14>Azure Kubernetes Service
**[#gold] ====Cloud Platforms
***[#yellow] ====<size:14>AWS
***[#yellow] ====<size:14>Azure
***[#yellow] ====<size:14>Google Cloud Platform
***[#yellow] ====<size:14>IBM Cloud
***[#yellow] ====<size:14>Oracle Cloud
@endmindmap