@startmindmap
title = __Kubernetes__
!theme hacker

* Core Components
** API Server
** etcd
** Controller Manager
** Scheduler
** Kubelet
** Kube-proxy
* Master Components
** kube-apiserver
** kube-controller-manager
** kube-scheduler
** etcd
* Node Components
** kubelet
** kube-proxy
* Addons
** Dashboard
** DNS
** Ingress Controller
** Metrics Server
** Network Policy Controller
** Storage Class Provisioner
* Cluster Architecture
** Nodes
***[#yellow] ====<size:14>Pods
***[#yellow] ====<size:14>Labels and Selectors
***[#yellow] ====<size:14>Namespaces
***[#yellow] ====<size:14>Services
***[#yellow] ====<size:14>Endpoints
***[#yellow] ====<size:14>Replication Controllers
***[#yellow] ====<size:14>Deployments
***[#yellow] ====<size:14>StatefulSets
***[#yellow] ====<size:14>DaemonSets
** Volumes
***[#yellow] ====<size:14>EmptyDir
***[#yellow] ====<size:14>HostPath
***[#yellow] ====<size:14>ConfigMap
***[#yellow] ====<size:14>Secrets
***[#yellow] ====<size:14>PersistentVolume
***[#yellow] ====<size:14>PersistentVolumeClaim
** Configurations
***[#yellow] ====<size:14>ConfigMaps
***[#yellow] ====<size:14>Secrets
** Security
***[#yellow] ====<size:14>Role-Based Access Control
***[#yellow] ====<size:14>Service Account
***[#yellow] ====<size:14>Network Policies
@endmindmap