@startmindmap
title =<i><b><u><size:18>Concurrency Patterns
!theme hacker

*[#darkblue] <i>Concurrency Patterns
**[#lightblue] <i><color #blac><size:12>Execution
***[#green] <b><i><color #white><size:12>Thread Pool
****[#yellow] <i><color #black><size:12>Fixed Thread Pool
****[#yellow] <i><color #black><size:12>Cached Thread Pool
****[#yellow] <i><color #black><size:12>Work Stealing Thread Pool
***[#green] <b><i><color #white><size:12>Fork/Join
****[#yellow] <i><color #black><size:12>RecursiveTask
****[#yellow] <i><color #black><size:12>RecursiveAction
**[#lightblue] <i><color #blac><size:12>Coordination
***[#green] <b><i><color #white><size:12>Barrier
****[#yellow] <i><color #black><size:12>Cyclic Barrier
****[#yellow] <i><color #black><size:12>Phaser
***[#green] <b><i><color #white><size:12>Latch
****[#yellow] <i><color #black><size:12>Count Down Latch
****[#yellow] <i><color #black><size:12>Concurrent Latch
***[#green] <b><i><color #white><size:12>Semaphore
****[#yellow] <i><color #black><size:12>Binary Semaphore
****[#yellow] <i><color #black><size:12>Counting Semaphore
**[#lightblue] <i><color #blac><size:12>Synchronization
***[#green] <b><i><color #white><size:12>Locks
****[#yellow] <i><color #black><size:12>Reentrant Lock
****[#yellow] <i><color #black><size:12>Read/Write Lock
***[#green] <b><i><color #white><size:12>Atomic Variables
****[#yellow] <i><color #black><size:12>Atomic Integer
****[#yellow] <i><color #black><size:12>Atomic Long
****[#yellow] <i><color #black><size:12>Atomic Reference
***[#green] <b><i><color #white><size:12>Concurrent Collections
****[#yellow] <i><color #black><size:12>Concurrent Hash Map
****[#yellow] <i><color #black><size:12>Concurrent Skip List Map
****[#yellow] <i><color #black><size:12>Copy On Write Array List
****[#yellow] <i><color #black><size:12>Concurrent Linked Queue
@endmindmap
