@startmindmap
title =<i><b><u>Data Parallelism
!theme hacker

*[#darkblue] <i> Data Parallelism
**[#lightblue] <i><color #blac><size:14>Definition
***[#yellow] <i><color #black><size:14>Breaking up a **large dataset** into smaller chunks and processing them simultaneously on multiple computing resources

***[#yellow] <i><color #black><size:14>**Example:** Dividing a large image into smaller sections and processing each section simultaneously on multiple processors
**[#lightblue] <i><color #blac><size:14>Benefits:
***[#yellow] <i><color #black><size:14>Faster processing of large datasets
***[#yellow] <i><color #black><size:14>Better utilization of available computing resources
***[#yellow] <i><color #black><size:14>Higher throughput and reduced processing time
***[#yellow] <i><color #black><size:14>Scalable and efficient processing of large datasets
**[#lightblue] <i><color #blac><size:14>Techniques
***[#yellow] <i><color #black><size:14>SIMD <b>(Single Instruction Multiple Data)
***[#yellow] <i><color #black><size:14>MIMD <b>(Multiple Instruction Multiple Data)
***[#yellow] <i><color #black><size:18>GPU <b>(Graphics Processing Unit)
***[#yellow] <i><color #black><size:14>FPGA <b>(Field-Programmable Gate Array)
***[#yellow] <i><color #black><size:18><b>Distributed processing
**[#lightblue] <i><color #blac><size:14>Applications
***[#yellow] <i><color #black><size:14>Image and video processing
***[#yellow] <i><color #black><size:14>Machine learning and deep learning
***[#yellow] <i><color #black><size:14>Scientific simulations and calculations
***[#yellow] <i><color #black><size:14>Big data processing and analytics
**[#lightblue] <i><color #blac><size:14>Frameworks and Libraries:
***[#yellow] <i><color #black><size:14>Apache Hadoop
***[#yellow] <i><color #black><size:14>Apache Spark
***[#yellow] <i><color #black><size:14>TensorFlow
***[#yellow] <i><color #black><size:14>PyTorch
***[#yellow] <i><color #black><size:14>CUDA <b>(Compute Unified Device Architecture)
***[#yellow] <i><color #black><size:14>OpenCL <b>(Open Computing Language)
@endmindmap
