@startmindmap
title =__Advance Economics__ \nThis mindmap covers topics related to microeconomics, including consumer theory, producer theory, and market equilibrium, as well as macroeconomics, including national income\n accounting, economic growth, money and banking, fiscal policy, international trade, and economic development. It includes subtopics such as budget constraints, utility maximization, demand curve,\n production function, cost function, profit maximization, supply curve, gross domestic product, comparative advantage, trade policies, and sustainable development goals.

* Advance Economics
**[#yellow] **Microeconomics**
*** Consumer Theory
**** Budget Constraints
**** Utility Maximization
**** Demand Curve
**** Indifference Curve
*** Producer Theory
**** Production Function
**** Cost Function
**** Profit Maximization
**** Supply Curve
*** Market Equilibrium
**** Perfect Competition
**** Monopoly
**** Oligopoly
**** Monopolistic Competition
**[#yellow] **Macroeconomics**
*** National Income Accounting
**** Gross Domestic Product
**** Net Domestic Product
**** National Income
**** Personal Income
*** Economic Growth
**** Solow Model
**** Endogenous Growth Model
**** Human Capital Model
*** Money and Banking
**** Functions of Money
**** Money Creation
**** Central Bank and Monetary Policy
*** Fiscal Policy
**** Government Spending
**** Taxation
**** Budget Deficit and Surplus
*** International Trade
**** Comparative Advantage
**** Trade Policies
**** Exchange Rates
*** Economic Development
**** Theories of Development
**** Human Development Index
**** Industrial Policy
**** Sustainable Development Goals

@endmindmap
