@startmindmap
title Linux Distros

* Family
** Debian-based
*** Debian
*** Ubuntu
*** Linux Mint
** Red Hat-based
*** Red Hat Enterprise Linux
*** Fedora
*** CentOS
** Arch-based
*** Arch Linux
*** Manjaro Linux
** SUSE-based
*** SUSE Linux Enterprise
*** openSUSE
** Gentoo-based
*** Gentoo Linux
*** Sabayon
** Slackware-based
*** Slackware
*** Slackel
** Others
*** Puppy Linux
*** Lubuntu
*** Zorin OS
*** Kali Linux

* Desktop Environments
** GNOME
** KDE Plasma
** Xfce
** LXDE
** Cinnamon
** MATE
** Unity
** Deepin
* Package Managers
** APT
** YUM/DNF
** Pacman
** Portage
** RPM
** Snap
* Server Distros
** Ubuntu Server
** Debian Server
** CentOS
** Red Hat Enterprise Linux
** openSUSE Leap
** SUSE Linux Enterprise Server
** Arch Linux


*[#yellow] **Package Management**
** Advanced Packaging Tools (APT)
** Yellowdog Updater Modified (YUM)
** PackageKit
** Snapcraft
** Flatpak
** RPM Package Manager
** Debian Package Manager
** Pacman Package Manager
** Zypper Package Manager
* System Configuration
** Systemd
** SELinux
** NetworkManager
** FirewallD
** Chrony
** Timeshift
** Swap Management
** Cron
** System Logs
** Sysctl
** Udev
** PAM
* File Systems
** Ext4
** Btrfs
** XFS
** ZFS
** OverlayFS
** GlusterFS
** CephFS
* Virtualization
** Kernel-based Virtual Machine (KVM)
** QEMU
** Xen
** VirtualBox
** Docker
** Podman
* Security
** SSH
** GnuPG
** AppArmor
** Firejail
** Tripwire
** ClamAV
** SELinux
* Networking
** Network File System (NFS)
** Secure Shell (SSH)
** Dynamic Host Configuration Protocol (DHCP)
** Domain Name System (DNS)
** Samba
** Apache
** NGINX
** HAProxy
** Cockpit
** VPN
** Wireshark
* Advanced Tools
** Bash Scripting
** Sed
** Awk
** Vim
** Emacs
** Git
** SVN
** Make
** CMake
** GDB
@endmindmap
