@startmindmap
title =Data Engineering\n<img:images/img.png> <img:images/img_1.png>\n <color #gold>All the underlined text with "white color" is clickable!
!theme hacker

* Data Engineering
** Definition
***[#a] ====<size:14>**Data engineering** is the process of designing, building, and maintaining data infrastructure, **[[data-pipeline/advanced-data-pipeline.puml pipelines]]**, and architectures to support **data-driven decision-making.**

**[#lime] Core Activities
***[#red] ====<size:14>**[[data-pipeline/Data-Ingestion.puml Data Ingestion]]**
****[#yellow] ====<size:14>Collect and bring data into a storage environment.
****[#yellow] ====<size:14>**Sources:** Databases, APIs, logs, files, and more.

***[#blue] ====<size:14>**[[data-preprocessing-(or-wrangling)/Data-Preprocessing.puml Data Transformation]]**
****[#yellow] ====<size:14>Clean, process, and structure data for analysis.
****[#yellow] ====<size:14>Includes data normalization, enrichment, and aggregation.

***[#crimson] ====<size:14>**[[data-storage-and-management/Data-Lake-vs-Data-Warehouse.puml Data Storage]]**
****[#yellow] ====<size:14>**__Design and manage__ data storage solutions.**
****[#red] ====<size:16>**Examples:** **[[../../../books/1-books-backlog/DBMS/dbms.puml Databases,]] [[data-storage-and-management/Data-Warehouse.puml Data Warehouses,]] [[data-storage-and-management/Data-Lake.puml data lakes,]] [[data-storage-and-management/Data-mart.puml data mart,]] [[data-storage-and-management/Data-Cube.puml data cube,]] [[data-storage-and-management/Delta-Lake.puml delta lake,]] [[data-storage-and-management/Data-Mesh.puml data mesh,]] [[data-storage-and-management/modeling-methodology/Data-Vault-vs-3NF-vs-Dimensional-Modeling.puml data vault,]] [[data-storage-and-management/DataOps.puml dataOps]]**.

***[#brown] ====<size:14>**[[data-preprocessing-(or-wrangling)/4-Data-Integration Data Integration]]**
****[#yellow] ====<size:14>Combine and unify data from various sources.
****[#yellow] ====<size:14>Ensure data consistency and accuracy.

*** ====<size:16>**[[Data-Processing.puml Data Processing]]**
****[#yellow] ====<size:14>Perform data computation and analysis.
****[#blue] ====<size:14>**May involve [[data-pipeline/Batch-Processing.puml batch]] and [[data-pipeline/Stream-Processing.puml stream processing.]]**

***[#lightgreen] ====<size:14>**[[Data-Governance.puml Data Governance]]**
****[#yellow] ====<size:14>Establish policies and procedures for data quality and compliance.
****[#yellow] ====<size:14>Ensure data security and privacy.

** Tools and Technologies
***[#green] ====<size:14>**[[../../../books/1-books-backlog/DBMS/Designing-Data-Intensive-Applications.puml Databases]]**
****[#afeaaa] ====<size:16>**[[../../../books/1-books-backlog/DBMS/Five-Basic-SQL-Joins.puml Relational databases]] (e.g., MySQL), [[../../../books/1-books-backlog/DBMS/NoSQL-Constructs.puml NoSQL databases]] (e.g., MongoDB), columnar stores (e.g., Cassandra)**.

***[#grey] ====<size:14>**[[data-storage-and-management/Data-Warehouse.puml Data Warehouses]]**
****[#black] ====<size:14>**Platforms like** **[[../../../cloud-computing/AWS-Cloud/Amazon-Redshift.puml Amazon Redshift,]]** **[[../../Apache-Big-Data-Ecosystem/Google-BigQuery.puml Google BigQuery,]] and** **[[../../Apache-Big-Data-Ecosystem/Snowflake.puml Snowflake.]]**

***[#orange] ====<size:14>**[[../../Apache-Big-Data-Ecosystem/1-Apache-Big-Data-Ecosystem.puml Big Data Technologies]]**
****[#lightgreen] ====<size:14>**[[../../Apache-Big-Data-Ecosystem/Hadoop.puml Apache Hadoop,]]** **[[../../Apache-Big-Data-Ecosystem/Apache-Spark.puml Spark,]] and** **[[../../Apache-Big-Data-Ecosystem/Hadoop-Distributed-File-System-(HDFS).puml distributed storage systems like HDFS.]]**

***[#black] ====<size:14>**[[../data-or-database-migration/Data-Migration-Strategies/ETL-(Extract-Transform-Load)-Strategy.puml ETL (Extract, Transform, Load) Tools]]**
****[#purple] ====<size:15>**Apache Nifi, Talend,** **[[../../Apache-Big-Data-Ecosystem/Apache-Beam.puml Apache Beam.]]**

***[#aaaaaa] ====<size:14>**[[data-pipeline/Stream-Processing-vs-Batch-Processing.puml Stream Processing]]**
****[#red] ====<size:14>**[[../../Apache-Big-Data-Ecosystem/apache-kafka.puml Apache Kafka,]]** **Apache Flink, Apache Storm.**

***[#crimson] ====<size:14>**[[data-storage-and-management/modeling-methodology/Data-Modeling.puml Data Modeling]]**
****[#black] ====<size:14>**Tools like [[../../../books/1-books-backlog/DBMS/erd-normalization.puml ERD diagrams]] and** **[[Schema-Design.puml schema design]].**

**[#lime] Considerations
*** ====<size:14>Scalability
****[#yellow] ====<size:14>Design for scalability to accommodate growing data volumes.

*** ====<size:14>Data Quality
****[#yellow] ====<size:14>Implement data validation and quality checks.

***[#a] ====<size:14>**Data Lineage**
****[#yellow] ====<size:14>Track the origin and transformation history of data.

*** ====<size:14>Compliance
****[#orange] ====<size:16>Ensure data complies with legal and industry regulations **(e.g., [[GDPR.puml GDPR]], [[HIPAA.puml HIPAA]])**.

*** ====<size:14>Data Security
****[#yellow] ====<size:14>Implement encryption, access controls, and data masking.

** Best Practices
***[#black] ====<size:14>**[[Data-Versioning.puml Data Versioning]]**
****[#orange] ====<size:14>**Maintain version control of data** and **[[data-pipeline/advanced-data-pipeline.puml pipelines]]**.

*** ====<size:14>Documentation
****[#pink] ====<size:14>Document data schemas, transformations, and **[[data-pipeline/advanced-data-pipeline.puml pipelines]]** configurations.

*** ====<size:14>Monitoring and Logging
****[#yellow] ====<size:14>Implement robust monitoring and logging to detect issues and performance bottlenecks.

*** ====<size:14>**Collaboration**
****[#orange] ====<size:16>Foster **collaboration** between **[[../11-key-areas-of-Data-Management-and-specific-data-roles/Data-Engineer.puml data engineers,]]** **[[../11-key-areas-of-Data-Management-and-specific-data-roles/Data-Scientist.puml data scientists,]] and** **[[../11-key-areas-of-Data-Management-and-specific-data-roles/Business-Analyst-vs-Data-Analyst.puml analysts.]]**

*** ====<size:14>**Automation**
****[#lightgreen] ====<size:14>**Automate data [[data-pipeline/advanced-data-pipeline.puml pipelines]] [[../../../3-programming-languages/architectural-characteristics/Deployability.puml (deployment)]], [[../../../books/1-books-backlog/software-testing/Levels-of-Testing.puml testing,]] [[../../../3-programming-languages/architectural-characteristics/Maintainability.puml and maintenance]].**

@endmindmap
