@startmindmap



*:|<img:48-new-data-structure-cheatsheet.png>|<img:47-algorithms-latest-cheatsheet.png>|
|<img:49-Graph-and-Array-data-structure-and-their-algorithms.png>|<img:50-Math-and-computer-science-cheatsheet.png>|;
@endmindmap
