@startmindmap
title =<i><b><u><size:18>Git Workflows\n|<img:images/img_10.png>|<img:images/Git.jpg{scale=.805}>|<img:images/img_18.png{scale=.61}>|
!theme hacker

*[#darkblue] <i>Git Workflows\n<img:images/img_1.jpeg{scale=.5}>
**[#lightblue] <i><color #blac><size:22>[[docs/3-devops/git/Pull-Request-Workflow.puml Pull request Workflow]]
***[#yellow] <i><color #black><size:12>is used along with other workflows or almost in every workflow
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Centralized-workflow.puml Centralized Workflow]]
***[#green] <b><i><color #white><size:12>Single Shared Repository
****[#yellow] <i><color #black><size:12>All developers commit to a single central repository.
***[#green] <b><i><color #white><size:12>Simple and Linear
****[#yellow] <i><color #black><size:12>Easy to understand and manage but lacks collaboration features.
***[#green] <b><i><color #white><size:12>Collaboration via Pull Requests
****[#yellow] <i><color #black><size:12>Developers propose changes through PRs for review and integration.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Feature-Branch-workflow.puml Feature Branch Workflow]]
***[#green] <b><i><color #white><size:12>Individual Branches for Features
****[#yellow] <i><color #black><size:12>Each feature developed in a dedicated branch.
***[#green] <b><i><color #white><size:12>Facilitates Parallel Development
****[#yellow] <i><color #black><size:12>Developers work on features concurrently.
***[#green] <b><i><color #white><size:12>Integration via Merge or Rebase
****[#yellow] <i><color #black><size:12>Feature branches merged into the main branch.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Gitflow-workflow.puml Gitflow Workflow]]
***[#green] <b><i><color #white><size:12>Long-lived Branches
****[#yellow] <i><color #black><size:12>**Main branches:** "master" "for production, "develop" for <b>ongoing work.
***[#green] <b><i><color #white><size:12>Feature, Release, and Hotfix Branches
****[#yellow] <i><color #black><size:12>Features in branches off "develop", releases in branches off "develop" "or "master", hotfixes off "master`.
***[#green] <b><i><color #white><size:12>Strict Branch Management
****[#yellow] <i><color #black><size:12>Specific branches for each phase of development.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/trunk-based-development-workflow.puml Trunk-based development Workflow]]
***[#a] <i><color #black><size:12><b>[[https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development CI/CD Trunk based development]] article
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Forking-workflow.puml Forking Workflow]]
***[#green] <b><i><color #white><size:12>Independent Repositories
****[#yellow] <i><color #black><size:12>Each developer forks the main repository, works in their own repository, and creates PRs to the main repository.
***[#green] <b><i><color #white><size:12>Enhanced Collaboration and Isolation
****[#yellow] <i><color #black><size:12>Enables contributors to work independently.
***[#green] <b><i><color #white><size:12>Integration via Pull Requests
****[#yellow] <i><color #black><size:12>Changes reviewed and merged through PRs to the main repository.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Gitlab-workflow.puml GitLab Flow]]
***[#green] <b><i><color #white><size:12>Continuous Integration Focus
****[#yellow] <i><color #black><size:12>Integration after successful testing via <b>CI/CD pipelines.
***[#green] <b><i><color #white><size:12>Main Branch Reflects Production
****[#yellow] <i><color #black><size:12>Main branch mirrors the state of production.
***[#green] <b><i><color #white><size:12>Continuous Delivery Emphasis
****[#yellow] <i><color #black><size:12>Changes deployed continuously to staging or production.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/GitHub-workflow.puml GitHub Flow]]
***[#green] <b><i><color #white><size:12>Single Branch (Usually `master`)
****[#yellow] <i><color #black><size:12>All work happens in a single branch.
***[#green] <b><i><color #white><size:12>Straightforward Workflow
****[#yellow] <i><color #black><size:12>Commits, PRs, Reviews, and Deploys are core actions.
***[#green] <b><i><color #white><size:12>Fast Iteration and Deployment
****[#yellow] <i><color #black><size:12>Emphasis on quickly shipping small, incremental changes.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Bitbucket-workflow.puml Bitbucket Flow]]
***[#green] <b><i><color #white><size:12>Branch per Task or Issue
****[#yellow] <i><color #black><size:12>Dedicated branches for each task or issue.
***[#green] <b><i><color #white><size:12>Similar to Feature Branch Workflow
****[#yellow] <i><color #black><size:12>Task-based branches merged back into the main branch.
***[#green] <b><i><color #white><size:12>Collaborative Code Review
****[#yellow] <i><color #black><size:12>Pull Requests for peer reviews and merging changes.
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Git-workflows-advantages.puml Advantages]]
***[#green] <b><i><color #white><size:12>Structured Collaboration
***[#green] <b><i><color #white><size:12>Enhanced Control and Clarity
***[#green] <b><i><color #white><size:12>Flexibility to Suit Project Needs
**[#lightblue] <i><color #blac><size:12>[[docs/3-devops/git/Git-Workflows-Considerations.puml Git workflows Considerations]]
**[#lightblue] <i><color #blac><size:12>Considerations
***[#green] <b><i><color #white><size:12>Complexity vs. Simplicity
***[#green] <b><i><color #white><size:12>Team Size and Structure
***[#green] <b><i><color #white><size:12>Project Scope and Requirements
**[#lightblue] <i><color #blac><size:12>Some things to consider when evaluating a Git workflow are:
***[#yellow] <i><color #black><size:12>Does this workflow scale with team size?
***[#yellow] <i><color #black><size:12>Is it easy to undo mistakes and errors with this workflow?
***[#yellow] <i><color #black><size:12>Does this workflow impose any new unnecessary cognitive overhead to the team?

@endmindmap
