@startmindmap
title =__<i> GitOps__ <size:9><i>(Taken from chatgpt-4)
!theme hacker




*[#darkblue] <i>GitOps
**[#lightblue] <i><color #blac><size:12>Principles
***[#green] <b><i><color #white><size:12>[[docs/3-devops/devops-plantuml-mindmap/infrastructure-as-code.puml Infrastructure as Code (IaC)]]
***[#green] <b><i><color #white><size:12>Version Control
***[#green] <b><i><color #white><size:12>Continuous Deployment
***[#green] <b><i><color #white><size:12>Automated Reconciliation
**[#lightblue] <i><color #blac><size:12>Components
***[#green] <b><i><color #white><size:12>Version Control System
****[#darkorange] <i><color #black><size:12><size:12><b>[[Git.puml Git]]
****[#yellow] <i><color #black><size:12><size:12>GitHub
****[#yellow] <i><color #black><size:12><size:12>GitLab
***[#green] <b><i><color #white><size:12>**Containerization**
****[#darkorange] <i><color #black><size:12><size:12>**[[docs/3-devops/devops-plantuml-mindmap/Docker.puml Docker]]**
***[#green] <b><i><color #white><size:12>**Orchestration**
****[#darkorange] <i><color #black><size:12><size:12>**[[docs/3-devops/devops-plantuml-mindmap/kubernetes.puml Kubernetes]]**
**[#lightblue] <i><color #blac><size:22>Workflow
***[#darkorange] <b><i><color #white><size:12>**Step 1:** Code Commit
***[#darkorange] <b><i><color #white><size:12>**Step 2:** CI/CD **Pipeline**
***[#darkorange] <b><i><color #white><size:12>**Step 3:** **Deployment**
***[#darkorange] <b><i><color #white><size:12>**Step 4:** Monitoring & Reconciliation
**[#lightblue] <i><color #blac><size:12>Benefits
***[#green] <b><i><color #white><size:12>Consistency
***[#green] <b><i><color #white><size:12>Traceability
***[#green] <b><i><color #white><size:12>Faster Recovery
***[#green] <b><i><color #white><size:12>Improved Security
**[#lightblue] <i><color #blac><size:12>Challenges
***[#green] <b><i><color #white><size:12>Initial Setup
***[#green] <b><i><color #white><size:12>Learning Curve
***[#green] <b><i><color #white><size:12>Security Concerns
**[#lightblue] <i><color #blac><size:12>Tools
***[#green] <b><i><color #white><size:12>**Flux**
***[#green] <b><i><color #white><size:12>**Argo CD**
***[#green] <b><i><color #white><size:12>**Jenkins X**
***[#green] <b><i><color #white><size:12>**Gitkube**
@endmindmap
