@startmindmap
title =<i><b><u>GitOps
!theme hacker

*[#darkblue] <i>GitOps
**[#lightblue] <i><color #black><size:12>Definition
***[#green] <b><i><color #white><size:12>GitOps is a  "software development methodology" that uses "Git" as the "source of truth" for "infrastructure" & "application deployment".
**[#lightblue] <i><color #black><size:12>Key Principles
***[#green] <b><i><color #white><size:12>Declarative Infrastructure
****[#yellow] <i><color #black><size:12>Infrastructure is defined in code, which can be version-controlled and automated.
***[#green] <b><i><color #white><size:12>Continuous Delivery
****[#yellow] <i><color #black><size:12>Changes to infrastructure and applications are automatically deployed from Git repositories.
***[#green] <b><i><color #white><size:12>Observability
****[#yellow] <i><color #black><size:12>The state of the system can be easily monitored and audited.
***[#green] <b><i><color #white><size:12>Self-Service
****[#yellow] <i><color #black><size:12>Developers can make changes to infrastructure and applications through Git, without needing to go through a central operations team.
**[#lightblue] <i><color #black><size:12>Benefits
***[#green] <b><i><color #white><size:12>Consistency
****[#yellow] <i><color #black><size:12>Infrastructure is always in the desired state, reducing errors and downtime.
***[#green] <b><i><color #white><size:12>Automation
****[#yellow] <i><color #black><size:12>Infrastructure and application deployment can be automated, saving time and effort.
***[#green] <b><i><color #white><size:12>Collaboration
****[#yellow] <i><color #black><size:12>Developers and operations teams can collaborate more easily, since infrastructure and application changes are made through Git.
***[#green] <b><i><color #white><size:12>Auditability
****[#yellow] <i><color #black><size:12>Changes to the system can be easily audited and tracked.
**[#lightblue] <i><color #black><size:12>Tools
***[#green] <b><i><color #white><size:12>Git
****[#yellow] <i><color #black><size:12>Used as the source of truth for infrastructure and application deployment.
***[#green] <b><i><color #white><size:12>Kubernetes
****[#yellow] <i><color #black><size:12>Used as the orchestration platform for deploying and managing containerized applications.
***[#green] <b><i><color #white><size:12>Flux
****[#yellow] <i><color #black><size:12>A GitOps tool that automates the deployment and management of Kubernetes applications.
***[#green] <b><i><color #white><size:12>Helm
****[#yellow] <i><color #black><size:12>A package manager for Kubernetes that can be used with GitOps workflows.
***[#green] <b><i><color #white><size:12>Argo CD
****[#yellow] <i><color #black><size:12>A GitOps tool that provides automated deployment and management of Kubernetes applications.
**[#lightblue] <i><color #black><size:12>Best Practices
***[#green] <b><i><color #white><size:12>Define infrastructure and application changes as code
***[#green] <b><i><color #white><size:12>Use Git to manage configuration and deployment
***[#green] <b><i><color #white><size:12>Automate deployment and rollback processes
***[#green] <b><i><color #white><size:12>Monitor system health and performance
***[#green] <b><i><color #white><size:12>Encourage collaboration between development and operations teams
@endmindmap
