@startmindmap
title = "Data Science" \n<img:images/img_18.png> <img:images/img_5.png>
!theme hacker

* Introduction
** Definition of Data Science
** The role of Data Scientist
** Skills required to be a Data Scientist

* **Data Collection**
** Sources of Data
**[#yellow] **Structured vs. Unstructured Data**
** Data Cleaning and Preprocessing
** Data Integration

* Data Analysis
**[#pink] **Exploratory Data Analysis (EDA)** e.g. using python **pandas library**
** Statistical Analysis
** Data Visualization
** Machine Learning

*[#orange] =Data Modelling
** Linear and Logistic Regression
** Decision Trees and Random Forest
** Clustering
** Neural Networks

* Data Deployment
** Model Deployment
** Model Monitoring and Maintenance
** Ethics and Privacy

*[#a] =Tools and Technologies
** Programming Languages
***[#gold] ====<size:13>Python
***[#gold] ====<size:13>R
***[#gold] ====<size:13>Java
***[#gold] ====<size:13>SQL
** Big Data Technologies
***[#gold] ====<size:13>Hadoop
***[#gold] ====<size:13>Spark
***[#gold] ====<size:13>Hive
** Data Science Platforms
***[#gold] ====<size:13>Azure Machine Learning
***[#gold] ====<size:13>Amazon SageMaker
***[#gold] ====<size:13>Google Cloud AI Platform

* Applications of Data Science
** Business Analytics
** Healthcare Analytics
** Fraud Detection
** Image and Speech Recognition
** Recommendation Systems

@endmindmap
