@startmindmap

title =__Developing Mind Maps is waste of time?__

* **I have developed a lot of mindmaps related to AI, ML, DL, system design, databases, cloud computing, DevOps, programming languages, requirements engineering, data science, math, politics, Islam, blockchain, **\n**distributed systems, and others. Is this good or a waste of time?**

* Developing mind maps on various topics can be a good way to organize and visualize information. It can help you to connect different ideas and concepts and create a comprehensive overview of a specific topic. \nIt also helps in retaining information for a longer time.

* Moreover, having knowledge in various domains can be an advantage in your personal and professional life. It can help you to have a broader perspective on different topics and can also make you a valuable asset \nin various industries.

* However, it's also important to balance the time spent on learning new things and applying them in practical scenarios. It's crucial to prioritize your tasks and focus on the skills that align with your career goals and \naspirations. So, developing mind maps on different topics is not a waste of time if it's done with a purpose and a clear plan of how to use that knowledge.

* =//Brainstorm//
**:As known as a Mind-map.

   A Brainstorm is a diagram used to map associated ideas, words, images and concepts together. Brainstorms are also a tool and method for idea generation, finding
   associations, classifying ideas, organising information, visualising structure and a general aid to studying. Brainstorms are often used at the initial stage of a project and work as a form of note-taking.
   They can also be useful in collaboration work and team-building morale.

   The structure of a Brainstorm is as follows: major categories extend out from a central node. Lesser categories branch out of the major ones as subcategories, which can also develop their own related subcategories.

   Here's a simple guide to creating a Brainstorm:

   1. Start in the center of a page and write the title of the project or topic by encapsulating it in a shape (typically a circle or cloud).
   2. Think of relevant, useful or related words or categories to the subject you are investigating.
   3. Then, for each category, draw extending out of the central title (in any direction), lines with the name of the category at the end.
   4. Now for each of the categories, think of any words that relate to it and draw in the same fashion as in the previous step.
   5. You can repeat step 4 for the new set of subcategories or highlight words if need be
   **[[https://datavizcatalogue.com/methods/brainstorm.html https://datavizcatalogue.com/methods/brainstorm.html]]**;
@endmindmap
