@startmindmap
title =__ Data Science__ \n<img:images/img_17.png>
!theme hacker

*[#gold] =Data Science\n<img:images/img_5.png>
**[#a] =**Foundations of Data Science**
***[#yellow] ====<size:13>Statistics
***[#yellow] ====<size:13>Linear Algebra
***[#yellow] ====<size:13>Probability Theory
***[#yellow] ====<size:13>Programming
** Data Manipulation
***[#yellow] ====<size:13>Data Cleaning
***[#yellow] ====<size:13>Data Integration
***[#yellow] ====<size:13>Data Transformation
** Data Visualization and Communication
***[#yellow] ====<size:13>Graphical Perception
***[#yellow] ====<size:13>Visual Encoding and Interaction
***[#yellow] ====<size:13>Visualization Design
**[#lightgreen] ==Machine Learning
***[#yellow] ====<size:13>Supervised Learning
***[#yellow] ====<size:13>Unsupervised Learning
***[#yellow] ====<size:13>Semi-Supervised Learning
***[#yellow] ====<size:13>Deep Learning
** =Big Data
***[#yellow] ====<size:13>Distributed Computing
***[#yellow] ====<size:13>Scalability
***[#yellow] ====<size:13>Storage Systems
***[#yellow] ====<size:13>Data Streaming
** Applications of Data Science
***[#yellow] ====<size:13>Natural Language Processing
***[#yellow] ====<size:13>Computer Vision
***[#yellow] ====<size:13>Social Network Analysis
***[#yellow] ====<size:13>Business Analytics
@endmindmap
