@startmindmap
title =__ NLP__
!theme hacker

* NLP
** Core Concepts
*** Syntax
****[#yellow] ====<size:13>Part of speech tagging
****[#yellow] ====<size:13>Parsing
*** Semantics
****[#yellow] ====<size:13>Named entity recognition
****[#yellow] ====<size:13>Sentiment analysis
****[#yellow] ====<size:13>Topic modeling
*** Discourse
****[#yellow] ====<size:13>Co-reference resolution
****[#yellow] ====<size:13>Coreference chains
** Applications
*** Machine Translation
*** Sentiment Analysis
*** Chatbots
*** Speech Recognition
*** Text Summarization
** Techniques
*** Rule-based
*** Machine Learning-based
****[#yellow] ====<size:13>Supervised learning
****[#yellow] ====<size:13>Unsupervised learning
****[#yellow] ====<size:13>Semi-supervised learning
****[#yellow] ====<size:13>Reinforcement learning
*** Deep Learning
****[#yellow] ====<size:13>Convolutional Neural Networks
****[#yellow] ====<size:13>Recurrent Neural Networks
****[#yellow] ====<size:13>Transformer
** Challenges
*** Ambiguity
*** Polysemy
*** Named entity disambiguation
*** Sentiment polarity
*** Language variation
@endmindmap
