:numbered:
:hardbreaks:
:sectnumlevels: 6
:sectids:
:sectanchors:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

== Specific requirements (organized by user object)

Objects are real-world entities that have a counterpart within the system. For example, in a patient monitoring system, objects include patients, sensors, nurses, rooms, physicians, medicines, etc. Associated with each object is a set of attributes (of that object) and functions (performed by that object). These functions are also called services, methods, or processes. Note that sets of objects may share attributes and services. These are grouped together as classes.

There are many notations, methods, and automated support tools available to aid in the documentation of requirements. For the most part, their usefulness is a function of organization. For example, when organizing by mode, finite state machines or state charts may prove helpful; when organizing by object, object-oriented analysis may prove helpful; when organizing by feature, stimulus-response sequences may prove helpful; and when organizing by functional hierarchy, data flow diagrams and data dictionaries may prove helpful.

This section of the SRS should contain all of the software requirements to a level of detail sufficient to enable designers to design a system to satisfy those requirements, and testers to test that the system satisfies those requirements. Throughout this section, every stated requirement should be externally perceivable by users, operators, or other external systems. These requirements should include at a minimum a description of every input (stimulus) into the system, every output (response) from the system, and all functions performed by the system in response to an input or in support of an output.

.As this is often the largest and most important part of the SRS, the following principles apply:
.. Specific requirements should be stated in conformance with all the characteristics of a good SRS.
An SRS should be
... Correct;
... Unambiguous; 
... Complete; 
... Consistent; 
... Ranked for importance and/or stability; 
... Verifiable; 
... Modifiable; 
... Traceable. 

.. Specific requirements should be cross-referenced to earlier documents that relate.
.. All requirements should be uniquely identifiable.
.. Careful attention should be given to organizing the requirements to maximize readability.

=== External interface requirements

This should be a detailed description of all inputs into and outputs from the software system. It should complement the interface descriptions in <<OverallDescription.adoc#trueoverall-description,Overall Description>> and should not repeat information there.

.It should include both content and format as follows:
.. Name of item;
.. Description of purpose;
.. Source of input or destination of output;
.. Valid range, accuracy, and/or tolerance;
.. Units of measure;
.. Timing;
.. Relationships to other inputs/outputs;
.. Screen formats/organization;
.. Window formats/organization;
.. Data formats;
.. Command formats;
.. End messages.

==== User interfaces
==== Hardware interfaces
==== Software interfaces
==== Communications interfaces
=== Classes/Objects
==== Class/Object 1
===== Attributes (direct or inherited)
====== Attribute 1
====== Attribute 2
====== Attribute 3
===== Functions (services, methods, direct or inherited)

Functional requirements should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. These are generally listed as "shall" statements starting with "The system shall..."

.These include
.. Validity checks on the inputs
.. Exact sequence of operations
.. Responses to abnormal situations, including
... Overflow
... Communication facilities
... Error handling and recovery
.. Effect of parameters
.. Relationship of outputs to inputs, including
... Input/output sequences
... Formulas for input to output conversion

It may be appropriate to partition the functional requirements into subfunctions or subprocesses. This does not imply that the software design will also be partitioned that way.

This section may be described in native language (e.g., English), in pseudocode, in a system denition language, or in four subsections titled: Introduction, Inputs, Processing, and Outputs. 

====== Functional requirement 1
====== Functional requirement 2
====== Functional requirement 3
===== Messages (communications received or sent)
==== Class/Object 2
===== Attributes (direct or inherited)
====== Attribute 1
====== Attribute 2
====== Attribute 3
===== Functions (services, methods, direct or inherited)

Functional requirements should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. These are generally listed as "shall" statements starting with "The system shall..."

.These include
.. Validity checks on the inputs
.. Exact sequence of operations
.. Responses to abnormal situations, including
... Overflow
... Communication facilities
... Error handling and recovery
.. Effect of parameters
.. Relationship of outputs to inputs, including
... Input/output sequences
... Formulas for input to output conversion

It may be appropriate to partition the functional requirements into subfunctions or subprocesses. This does not imply that the software design will also be partitioned that way.

This section may be described in native language (e.g., English), in pseudocode, in a system denition language, or in four subsections titled: Introduction, Inputs, Processing, and Outputs. 

====== Functional requirement 1
====== Functional requirement 2
====== Functional requirement 3
===== Messages (communications received or sent)
==== Class/Object 3
===== Attributes (direct or inherited)
====== Attribute 1
====== Attribute 2
====== Attribute 3
===== Functions (services, methods, direct or inherited)

Functional requirements should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. These are generally listed as "shall" statements starting with "The system shall..."

.These include
.. Validity checks on the inputs
.. Exact sequence of operations
.. Responses to abnormal situations, including
... Overflow
... Communication facilities
... Error handling and recovery
.. Effect of parameters
.. Relationship of outputs to inputs, including
... Input/output sequences
... Formulas for input to output conversion

It may be appropriate to partition the functional requirements into subfunctions or subprocesses. This does not imply that the software design will also be partitioned that way.

This section may be described in native language (e.g., English), in pseudocode, in a system denition language, or in four subsections titled: Introduction, Inputs, Processing, and Outputs. 

====== Functional requirement 1
====== Functional requirement 2
====== Functional requirement 3
===== Messages (communications received or sent)

