@startmindmap
title = __ Scalability__
!theme hacker

* Scalability
** Horizontal
***[#gold] ====<size:14>Load balancing
***[#gold] ====<size:14>Stateless architecture
***[#gold] ====<size:14>Microservices
** Vertical
***[#gold] ====<size:14>Scaling up hardware
***[#gold] ====<size:14>Optimizing code and algorithms
** Diagonal
***[#gold] ====<size:14>Combination of horizontal and vertical scaling
***[#gold] ====<size:14>Auto-scaling
***[#gold] ====<size:14>Elasticity
** Challenges
***[#gold] ====<size:14>Bottlenecks
***[#gold] ====<size:14>Database scalability
***[#gold] ====<size:14>Network latency
@endmindmap
