@startmindmap
* <b><i>[[https://www.youtube.com/watch?v=W2Z7fbCLSTw&list=LL&index=3 Database Paradigms]] 7-min YouTube
title  = <i><size:18>Designing Data-Intensive Applications
!theme hacker

*[#darkblue] <i><color #white>Designing Data-Intensive \n<i><color #white>Applications
**[#lightblue]:<size:12><i>Choose the right __data model__
<size:12><i>for your application
====
*<size:12><i>[[https://www.youtube.com/watch?v=W2Z7fbCLSTw&list=LL&index=3 Database Paradigms]] 7-min;
***[#green] <size:22><i><color #white><b>Data Model \n<b><i>[[https://www.youtube.com/watch?v=W2Z7fbCLSTw&list=LL&index=3 Database Paradigms]]
****[#orange] <color #black><size:12><i>**1- Hierarchical**
****[#orange] <color #black><size:12><i>**2- Network**
****[#orange] <color #black><size:18><i>**3- Relational (SQL) + ACID**
*****[#yellow] <size:18><i><b>Schema-based database
******[#a]:*<size:12><i><b>[[https://www.youtube.com/watch?v=UrYLYV7WSHM&t=39s Normalization: 1NF, 2NF, 3NF and 4NF]]
**<size:12><i><b>[[https://www.youtube.com/watch?v=SK4H5tTT6-M&t=278s 1NF, 2NF, 3NF]]
**<size:12><i><b>[[https://www.youtube.com/watch?v=GFQaEYEc8_8&t=1247s 1NF, 2NF, 3NF, 4NF, and 5NF]]
*<size:12><i><b>[[https://www.youtube.com/watch?v=BHwzDmr6d7s&t=99s Secret To Optimizing SQL Queries - Understand The SQL Execution Order]]
*<size:12><i><b>[[docs/books/1-books-backlog/DBMS/SQL-Constructs.puml SQL Constructs]];

*****[#yellow] <size:18><i><b>Types
******[#yellow]  **Relational**
*******:* <b>SQL Server
* <b>My SQL
* <b>Oracle
* <b>Postgres
* <b>SQL Compact;
******[#yellow]  **Analiticals (OLAP)**
****[#orange] <color #black><size:18><i>**4- Non-Relational (No-SQL) + BASE**
*****[#yellow] <size:18><i><b>Schema-less database
*****[#yellow] <size:18><i><b>Types

******[#yellow] **Key-Value**
*******:*<b>redis
*<b>memcached
*<b>ignite
*<b>riak;
******[#yellow] **Wide-column**
*******:*<b>cassandra
* <b>Apache HBase;

******[#yellow] **Document**
*******:* <b>Mongo DB
* <b>Couch DB
* <b>Arango DB
* <b>RAVEN DB;

******[#yellow] **Graph**
*******:*<b>neo4j
*<b>AllergoGraph;


***[#green] <size:12><i><color #white>Each **__data model__** has its own **strengths and weaknesses**
***[#green] <size:22><i><color #white>**__The choice of //data model// can significantly impact //performance and scalability//__**
**[#lightblue] <size:12><i>Data __storage__ and __retrieval__
***[#green] <size:12><i><color #white>**__Techniques__** include **indexing, caching, and compression**
***[#green] <size:12><i><color #white>__**Choice of storage technique can impact performance and scalability**__
**[#lightblue] <size:12><i>Data processing
***[#green] <size:12><i><color #white>Covers **batch processing and stream processing**
***[#green] <size:12><i><color #white>**__Techniques__** include **MapReduce and Apache Kafka**
****[#orange] <color #black><size:12><i> **Apache beam** can do **stream and batch processing** & is open source plus latest **technology**. \n<size:12><i><color #black>It is a **polyglot** tool (meaning works flawlessly with different programing languages)
***[#green] <size:12><i><color #white>Emphasizes importance of **fault tolerance**
**[#lightblue] <size:12><i>Distributed systems
***[#green] <size:12><i><color #white>Includes **distributed databases, messaging, and consensus algorithms**
***[#green] <size:12><i><color #white>Emphasizes importance of **fault tolerance and replication**
**[#lightblue] <size:12><i>Scalability
***[#green] <size:12><i><color #white>**__Techniques__** include **sharding, partitioning, and replication**
***[#green] <size:12><i><color #white>Emphasizes importance of **horizontal scalability**
**[#lightblue] <size:12><i> Reliability
***[#green] <size:12><i><color #white>**__Techniques__** include **replication, consensus algorithms, and failure detection**
***[#green] <size:12><i><color #white>Emphasizes importance of **designing for failure**
**[#lightblue] <size:12><i>Performance
***[#green] <size:12><i><color #white>Guidance on **optimizing latency, throughput, and resource utilization**
**[#lightblue] <size:12><i>Trade-offs
***[#green] <size:12><i><color #white>**__Every design decision involves trade-offs__**
***[#green] <size:12><i><color #white>**Encourages making informed choices**

@endmindmap

