@startmindmap
* Contents ⭐
** Introduction [0:00:00]
** What is a Database? [0:03:12]
** What is a Relational Database? [0:11:04]
** RDBMS [0:23:42]
** Introduction to SQL [0:37:32]
** Naming Conventions [0:44:01]
** What is Database Design? [0:47:16]
** Data Integrity [1:00:26]
** Database Terms [1:13:28]
** More Database Terms [1:28:28]
** Atomic Values [1:38:46]
** Relationships [1:44:25]
*** One-to-One Relationships [1:50:35]
*** One-to-Many Relationships [1:53:45]
*** Many-to-Many Relationships [1:57:50]
*** Designing One-to-One Relationships [2:02:24]
*** Designing One-to-Many Relationships [2:13:40]
*** Parent Tables and Child Tables [2:23:50]
*** Designing Many-to-Many Relationships [2:30:42]
*** Summary of Relationships [2:46:23]
** Introduction to Keys [2:54:42]
** Primary Key Index [3:07:24]
** Look up Table [3:13:42]
** Superkey and Candidate Key [3:30:19]
** Primary Key and Alternate Key [3:48:59]
** Surrogate Key and Natural Key [3:56:34]
** Should I use Surrogate Keys or Natural Keys? [4:03:43]
** Foreign Key [4:13:07]
** NOT NULL Foreign Key [4:25:15]
** Foreign Key Constraints [4:38:17]
** Simple Key, Composite Key, Compound Key [4:49:50]
** Review and Key Points [5:01:54]
** Introduction to Entity Relationship Modeling [5:10:28]
** Cardinality [5:17:34]
** Modality [5:24:41]
** Introduction to Database Normalization [5:35:14]
*** 1NF (First Normal Form of Database Normalization) [5:39:48]
*** 2NF (Second Normal Form of Database Normalization) [5:46:34]
*** 3NF (Third Normal Form of Database Normalization) [5:55:00]
** Indexes (Clustered, Nonclustered, Composite Index) [6:01:12]
** Data Types [6:14:36]
** Introduction to Joins [6:25:55]
*** Inner Join [6:39:23]
*** Inner Join on 3 Tables [6:54:48]
*** Inner Join on 3 Tables (Example) [7:07:41]
** Introduction to Outer Joins [7:23:53]
*** Right Outer Join [7:29:46]
*** JOIN with NOT NULL Columns [7:35:33]
*** Outer Join Across 3 Tables [7:42:40]
** Alias [7:48:24]
** Self Join [7:52:13]
@endmindmap
