@startmindmap
title = __2 types of client__\nIt is must retain the client in freelancing or in any other business, otherwise you can never scale your business.

*[#a] =2-Regions of client
** Clients from Middle East
*** ====Bahrain, Cyprus, Egypt, Iran, Iraq, Israel, Jordan, Kuwait, Lebanon, Oman, Palestine,Qatar, Saudi Arabia, Syria, Turkey, United Arab Emirates, Yemen, etc.
** Clients from West
***:====The West is a broad term that can refer to different regions and cultures depending on the context. However, in general, it is used to describe the countries
 //of North America and Europe, as well as Oceania.//,

Here is a list of the countries in the West, in alphabetical order:

//Andorra, **Australia, **Austria, Belgium, **Canada,** Denmark, Finland, **France, Germany,** Greece, Iceland, **Ireland, Italy,** Liechtenstein, //
//Luxembourg, Malta, Monaco, Netherlands, New Zealand, Norway, Portugal, San Marino, **Spain, Sweden, Switzerland, United Kingdom, United States**//;

*[#a] =2-types of client
**[#a] =0 and 1
***[#pink] ==Usually From West Region
****://With these clients you 've the margin that if something did not remain in your favour you can bring it back to your favour after re-strategize it //
//You can achieve this only when you will do something out of the box for them. You should give an attempt these people often give value. //
===//Don't try to apply this theory to client from Middle-East//;
****:When you understand in the **freelancing/business world** that:
1- How to deal a specific client?
2- How much you should communicate to a specific client?
3- How much information should be given to a specific client?
4- To what extent you remain professional to a specific client?;
***** Have mastery of these & your life will will become much more easier
***[#yellow] =0
**** While talking in negotiation, communication, pre-negotiation, project execution
*****[#lightyellow] ===Something they don't like, something not in your favour
*****[#lightyellow] So you 've to understand when this happens then the client\ndoes not listen you and does not give you value or does not\ntake you seriously
*****[#gold] But still client is not judging you, not showing ego, not becoming negative,\nnot going against you, is not reacting, is not becoming irrational
***[#lime] =1
**** While talking in negotiation, communication, pre-negotiation, project execution
***** Something they like, something in your favour
*****[#lightgreen] If the client likes what you said and agrees with you\nthen he will give you value/benefit
*****[#gold] But still client is not judging you, not showing ego, not becoming negative,\nnot going against you, is not reacting, is not becoming irrational

** =-1 and 1
***[#pink] ==Usually From Middle-East Region
***[#red] =-1
****[#red] ===if they don't understand what you are saying they will react abruptly & cancel the project.
*****:Actually when you come in contact with a client it goes through a **very**
**very long conversation** containing **pre-negotiation, negotiation, **
**specification, and answers to lot of questions**  & **now when this**
**project is about to close** and are just 5-minutes late in a meeting,
client feels his insult and thinks he is not the right person, and all the
hard work goes in vain. such clients are <size:18> **-1**;
****[#yellow] ==Treat them carefully
*****[#red] ==Be careful in selection of your words, must choose them carefully
*****[#red] ==Avoid overflow of information
******[#red] ===Meaning don't tell them more than necessary about something
******[#red] ===Meaning don't do overselling
******[#red] ===Meaning don't answer a question more than necessary
***[#lime] =1
**** While talking during negotiation, communication, pre-negotiation, project execution
***** Something they like, something in your favour
*****[#lightgreen] If the client likes what you said and agrees with you\nthen he will give you value/benefit
*****[#gold] But still client is not judging you, not showing ego, not becoming negative,\nnot going against you, is not reacting, is not becoming irrational
@endmindmap
