@startmindmap

title This mindmap outlines the key beliefs, practices, schools of thought, and holidays and observances of the Shia sect of Islam. It also includes information about the three main sub-sects \nwithin Shia Islam: Twelver, Ismaili, and Zaidi.






* Shia Sect
** Beliefs
*** Imamat
**** 12 Imams
**** Ali as the first Imam
**** Mahdi - the twelfth and final Imam
*** Authority of the Prophet's family
*** Taqiyya - the practice of concealing one's faith
*** Mourning of Muharram
*** Karbala incident
** Practices
*** Salah
**** Adhan
**** Takbir
**** Rakat
*** Sawm - Fasting during Ramadan
*** Khums - Paying one-fifth of excess income
*** Hajj - Pilgrimage to Mecca
*** Zakat - Giving to charity
** Schools of Thought
*** Twelver
**** Most populous and widely followed
**** Belief in 12 Imams
**** Imamate is a fundamental tenet
*** Ismaili
**** Believe in 7 Imams
**** Imamat is important but not fundamental
**** Concentrated in South Asia and East Africa
*** Zaidi
**** Believe in 5 Imams
**** Imamat is important but not fundamental
**** Concentrated in Yemen
** Holidays and Observances
*** Eid al-Fitr
*** Eid al-Adha
*** Ashura
*** Arba'een
@endmindmap
