@startmindmap

title This mindmap includes information on the beliefs, origins, schools of thought, practices, major holidays, and influential scholars of the Sunni sect of Islam. It also includes specific details about the Five Pillars \nof Islam and the four main schools of thought within Sunni Islam.






* Sunni Sect
** Beliefs
*** Five Pillars of Islam
**** Shahada
**** Salat
**** Zakat
**** Sawm
**** Hajj
*** Tawhid
*** Prophethood
*** Angels
*** Books of God
*** Divine Decree
** Origins
*** Emerged in the 7th century
*** Founded by Abu Bakr
*** Majority of Muslims are Sunnis
** **Schools of Thought**
*** Hanafi
**** Founded by Abu Hanifa
**** Prevalent in Turkey, Central Asia, India, and Pakistan
*** Maliki
**** Founded by Malik ibn Anas
**** Prevalent in North Africa and some parts of West Africa
*** Shafi'i
**** Founded by Muhammad al-Shafi'i
**** Prevalent in Egypt, Indonesia, and Southeast Asia
*** Hanbali
**** Founded by Ahmad ibn Hanbal
**** Prevalent in Saudi Arabia and some parts of Qatar and Kuwait
** Practices
*** Congregational prayers
*** Fasting during Ramadan
*** Pilgrimage to Mecca
*** Charity
*** Personal prayer and devotion
** Major Holidays
*** Eid al-Fitr
*** Eid al-Adha
** **Influential Scholars**
*** Imam Bukhari
*** Imam Muslim
*** Imam Abu Dawud
*** Imam Tirmidhi
*** Imam Ibn Majah
@endmindmap
