@startmindmap
title =Neural Networks Cheatsheet
!theme hacker
*[#lime] =Activation Functions (or neurons) both words can be used interchangeably

* Neural Networks
** Basics
*** Neurons and Activation Functions
*** Weights and Biases
*** Layers **(Input, Hidden, Output)**
*** Feedforward and Backpropagation

** Types
*** Feedforward Neural Networks **(FNN)**
*** Convolutional Neural Networks **(CNN)**
*** Recurrent Neural Networks **(RNN)**
*** Long Short-Term Memory **(LSTM)**
*** Gated Recurrent Units **(GRU)**

** Layer Types
*** Input Layer
****[#yellow] Fully Connected **(Dense)** Layers
****[#yellow] Convolutional Layers
****[#yellow] Recurrent Layers
*** Output Layer

** Activation Functions (or neurons)
*** Sigmoid
*** Hyperbolic Tangent **(tanh)**
*** Rectified Linear Unit **(ReLU)**
*** Leaky ReLU **(LReLU)**
*** Exponential Linear Unit **(ELU)**

** Loss Functions
*** Mean Squared Error **(MSE)**
*** Cross-Entropy Loss
*** Hinge Loss
*** Huber Loss
*** Custom Loss Functions

** Optimizers
*** Gradient Descent
*** Stochastic Gradient Descent **(SGD)**
*** Adam Optimizer
*** RMSprop
*** Adagrad

** Regularization
*** L1 Regularization **(Lasso)**
*** L2 Regularization **(Ridge)**
*** Dropout
*** Batch Normalization
*** Weight Decay

** Training and Validation
*** Training Data and Batches
*** Learning Rate
*** Early Stopping
*** Overfitting and Underfitting
*** Validation and Testing

** Applications
*** Image Classification
*** Natural Language Processing **(NLP)**
*** Speech Recognition
*** Computer Vision
*** Autonomous Vehicles

** Frameworks and Libraries
*** TensorFlow
*** PyTorch
*** Keras
*** scikit-learn
*** Caffe

** Challenges and Advanced Concepts
*** Vanishing and Exploding Gradients
*** Gradient Clipping
*** Transfer Learning
*** Generative Adversarial Networks **(GANs)**
*** Reinforcement Learning with Neural Networks

** Interdisciplinary Fields
*** Artificial Intelligence **(AI)**
*** Machine Learning **(ML)**
*** Deep Learning
*** Cognitive Computing
*** Neural Network Hardware

** Ethical and Legal Considerations
*** Bias and Fairness
*** Privacy Concerns
*** Regulatory Compliance
*** Responsible AI

** Future Developments
*** Architectural Innovations
*** Explainable AI **(XAI)**
*** Human-Machine Collaboration
*** Integration with IoT
*** Quantum Computing and Neural Networks

** Research Areas and Unsolved Problems
*** Explainability in Deep Learning
*** Compositional and Symbolic Reasoning
*** AI Safety and Robustness
*** Generalization in Neural Networks
*** Conscious AI and Cognitive Science

@endmindmap
