@startmindmap
title = __Asrar-i-Khudi (Secrets of the Self) by Dr. Allama Iqbal__

* Asrar-i-Khudi (Secrets of the Self)
** Introduction
** The Self and Its Development
*** The Nature of Self
*** The Need for Self-Knowledge
*** The Importance of Self-Realization
**[#yellow] **The Principle of Movement in the Structure of Islam**
***[#pink] **The Importance of Movement**
***[#pink] **The Principle of Movement in Islam**
***[#pink] **The Dynamic Nature of Islamic Culture**
** The Principle of Polarity in the Structure of the Universe and its Reflection in the Structure of the Ego
*** The Principle of Polarity in the Universe
*** The Principle of Polarity in the Self
*** The Balance Between Opposites
** **The Principle of Evolution in the Life of Man**
*** The Importance of Evolution
*** The Nature of Evolution
*** The Stages of Evolution
** **The Principle of Immortality in the Structure of the Self**
*** The Concept of Immortality
*** The Immortality of the Self
*** The Importance of the Idea of Immortality
** Conclusion
** Bibliography
@endmindmap
