. https://www.youtube.com/watch?v=vF_18ZsM1lE&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA. Helen's Take On: Generating Code]

. https://www.youtube.com/watch?v=Sio9MdSqXZo&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA. Helen's Take On: Writing Less Code]

. https://www.youtube.com/watch?v=AOrnx-9zNBQ&ab_channel=IntelliJIDEAbyJetBrains[Advanced Debugger Features in IntelliJ IDEA (Mala Gupta)]

. https://www.youtube.com/watch?v=AOrnx-9zNBQ&ab_channel=IntelliJIDEAbyJetBrains[Advanced Debugger Features in IntelliJ IDEA (Mala Gupta)]

. https://www.youtube.com/watch?v=2sDCA25qfKk&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA. Helen's Take On: Moving Around Your Codebase]

. https://www.youtube.com/watch?v=nqb9yAecM9Y&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA: Managing Dependencies]

. https://www.youtube.com/watch?v=l0ii-Oo0XX8&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA. Helen's Take On: Using Multiple Carets]

. https://www.youtube.com/watch?v=IsrTURTawAk&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA. Helen's Take On: Split Windows]


. https://www.youtube.com/watch?v=rPq7fBo5JVs&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA. Everyday Refactorings]

. https://www.youtube.com/watch?v=Au6NTrpTr_o&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA Pro Tips: Inject Language or Reference]


. https://www.youtube.com/watch?v=15uwUgqaEE4&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA Pro Tips: Local History]


. https://www.youtube.com/watch?v=wvo9aXbzvy4&ab_channel=IntelliJIDEAbyJetBrains[IntelliJ IDEA Pro Tips: Postfix Completion]

. https://www.youtube.com/watch?v=_Y1y8k-OTCQ&ab_channel=IntelliJIDEAbyJetBrains[*IntelliJ IDEA. Tips for Writing Code*]


. https://www.youtube.com/watch?v=1UHsJyCq1SU&ab_channel=IntelliJIDEAbyJetBrains[*Navigation in IntelliJ IDEA*]

. https://www.youtube.com/watch?v=lgZRMCpfYM4&ab_channel=IntelliJIDEAbyJetBrains[*IntelliJ IDEA 2020.2 for Java Developers*]

Extreme IntelliJ shortcuts https://www.youtube.com/watch?v=BW2dKuMducc&t=3519s[58:39]

=====
*Chapters*

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=30s[0:30]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=37s[Create a New Project]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=37s[0:37]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=48s[New Project Wizard]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=48s[0:48]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=88s[Live Templates]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=88s[1:28]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=216s[Rearrange Code]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=216s[3:36]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=284s[Enhanced for Loop]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=284s[4:44]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=298s[Writing Test Classes]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=298s[4:58]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=331s[Post Fix Completion]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=331s[5:31]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=395s[Local History]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=395s[6:35]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=484s[Cut and Paste Content]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=484s[8:04]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=511s[Manipulate Strings]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=511s[8:31]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=541s[Multiple Cursors]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=541s[9:01]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=550s[Column Select Mode]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=550s[9:10]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=742s[Jump between Errors]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=742s[12:22]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=778s[Change the Method Declaration]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=778s[12:58]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=917s[Inspections]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=917s[15:17]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=922s[Java 8 Refactorings]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=922s[15:22]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=945s[Refactoring]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=945s[15:45]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=951s[Extracting and Inlining Methods]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=951s[15:51]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=999s[Inline Code]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=999s[16:39]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1045s[Inline Variables]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1045s[17:25]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1091s[Refactor a Class]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1091s[18:11]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1125s[Parameter Hints]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1125s[18:45]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1202s[Find Usages]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1202s[20:02]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1232s[Keyboard Shortcuts]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1232s[20:32]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1320s[Search Everywhere]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1320s[22:00]

These chapters are auto-generated

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=136s[Writing Code]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=136s[2:16]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=417s[Manipulating Code]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=417s[6:57]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=664s[IntelliJ IDEA'S Intelligence]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=664s[11:04]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=937s[Refactoring Code]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=937s[15:37]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1111s[Reading Code]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1111s[18:31]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1267s[Navigating]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1267s[21:07]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1398s[Configuring IntelliJ IDEA]

https://www.youtube.com/watch?v=Lw2yBw6KsJs&t=1398s[23:18]

=====

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=0s[00:00] - Intro

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=11s[00:11] - Presentation Assistant plugin

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=57s[00:57] - Presentation Mode

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=126s[02:06] - Mouse Zoom

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=163s[02:43] - Font

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=191s[03:11] - Theme

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=228s[03:48] - Tool windows

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=313s[05:13] - Find Action & Soft-wrap

https://www.youtube.com/watch?v=h-HGg9b6Dqw&t=358s[05:58] - Shortcuts & Navigation






