@startmindmap
title =__ Team Lead__

* Team Lead
** Leadership Skills
*** Communication
*** Conflict Resolution
*** Time Management
*** Decision Making
*** Motivation
** Technical Skills
*** Software Design
*** Architecture
*** Project Management
*** Quality Assurance
*** Team Management
** Process Management
*** Agile Methodologies
*** Scrum
*** Kanban
*** Continuous Integration (CI)
*** Continuous Deployment (CD)
** Business Management
*** Budgeting and Resource Allocation
*** Marketing and Sales
*** Client Management
*** Strategic Planning
*** Risk Management
@endmindmap
