@startmindmap

title = __Science__

* Science
** Branches of Science
*** Physical Sciences
**** Physics
**** Chemistry
**** Astronomy
**** Geology
*** Life Sciences
**** Biology
**** Botany
**** Zoology
**** Ecology
**** Genetics
**** Neuroscience
**** Microbiology
**** Biochemistry
**** Biophysics
**** Biotechnology
*** Social Sciences
**** Psychology
**** Sociology
**** Anthropology
**** Political Science
**** Economics
**** History
**** Linguistics
**** Law
** Scientific Method
*** Observation
*** Hypothesis
*** Experimentation
*** Analysis
*** Conclusion
** Science Education
*** Science Curriculum
*** Science Experiments
*** Science Fairs
*** Science Education Resources
** Science and Technology
*** Innovation
*** Technology Development
*** Applied Science
*** Ethics of Science and Technology
** Famous Scientists
*** Isaac Newton
*** Albert Einstein
*** Galileo Galilei
*** Charles Darwin
*** Marie Curie
*** Stephen Hawking
*** Nikola Tesla
*** Johannes Kepler

@endmindmap
