@startmindmap
skinparam node {
    FontStyle italic
}

title =__ Professor Leonard Statistics-course__

*:**Topics:**
* Data Analysis and Interpretation,
* Data Descriptors,
* Probability,
* Binomial and Normal Distributions,
* Confidence Intervals,
* and Hypothesis testing with One Sample.;

@endmindmap
