@startmindmap
!define AWESOME mindmap

 skinparam {
  DefaultFontName Arial
  BackgroundColor gold
  DefaultFontSize 12
  DefaultLineColor DEFAULT_LINE_COLOR
  DefaultTextColor DEFAULT_TEXT_COLOR
}

title =__**Blockchain System Design**__
!theme hacker

+[#darkblue] <i>**Blockchain System Design**
++[#lightblue] <i><size:18>**Consensus Algorithms**\n<img:img_2.png>
+++[#green] <i><size:14><color #white>**Proof of Work (PoW)**
****[#orange] <i><size:14><color #black>is done by **miners,** who compete to create new blocks filled with processed transactions. \n<i><size:14><color #black>There is a race of who will solve the fastest a **mathematical puzzle.**This **puzzle** is the **work** \n<i><size:14><color #black>in **proof of work consensus mechanism** and produces the cryptographic link between the \n<i><size:14><color #black>current block and the previous block.
+++[#green] <i><size:14><color #white>**Proof of Stake (PoS)**
****[#orange] <i><size:14><color #black>done by **validators** who have staked cryptocurrency to participate in the system. For a new \n<i><size:14><color #black>block to be created, a random validator node is chosen. When a new block is created, it is \n<i><size:14><color #black>shared among the network and the selected validator node earns rewards.
+++[#green] <i><size:14><color #white>**Delegated Proof of Stake (DPoS)**
+++[#green] <i><size:14><color #white>**Practical Byzantine Fault Tolerance (PBFT)**
+++[#green] <i><size:14><color #white>**Federated Byzantine Agreement (FBA)**
+++[#green] <i><size:14><color #white>**Proof of Authority (PoA)**
****[#orange] <i><size:14><color #black>In a permissioned blockchain network all nodes are pre-authenticated which allows to use \n<i><size:14><color #black>consensus mechanisms which provide high transaction rate and other benefits. **Proof of **\n<i><size:14><color #black>**Authority** is one of them and it is an algorithm that provides high performance and fault \n<i><size:14><color #black>tolerance through a consensus mechanism based on identity as a stake. So, in PoA only \n<i><size:14><color #black>nodes that have proven their identity are awarded to create new blocks and the only way \n<i><size:14><color #black>to gain this right is to pass preliminary authentication.
+++[#green] <i><size:14><color #white>**Proof of Elapsed Time (PoET)**

++[#lightblue] <i><size:14>Cryptography
+++[#green] <i><size:14><color #white>**Public Key Cryptography**
+++[#green] <i><size:14><color #white>**Private Key Cryptography**
+++[#green] <i><size:14><color #white>**Digital Signatures**
+++[#green] <i><size:14><color #white>**Hash Functions**
****[#orange] <i><size:14><color #black>**SHA-256**
****[#orange] <i><size:14><color #black>Scrypt
****[#orange] <i><size:14><color #black>Ethash

++[#lightblue] <i><size:14>Blockchain Components
+++[#green] <i><size:18> <color #white>**Blocks** \n<img:img.png>**
****[#orange] <i><size:14><color #black>Block Header
*****[#yellow] <i><size:14>Previous Block Hash
*****[#yellow] <i><size:14>Merkle Tree Root Hash
*****[#yellow] <i><size:14>Timestamp
*****[#yellow] <i><size:14>Nonce
++++++[#yellow] <i><size:14>is a **32-bit** number. It is randomly generated when a new block\n<i><size:14><color #black>is created, which then generated a block header hash.\n* <i><size:14><color #black>The **hash**, a **256-bit** number wedded (married) to the **"nonce"**
*****[#yellow] <i><size:14>Difficulty Target
****[#orange] <i><size:14><color #black>Transactions
+++[#green] <i><size:14><color #white>**Transactions**
****[#orange] <i><size:14><color #black>Inputs
****[#orange] <i><size:14><color #black>Outputs
****[#orange] <i><size:14><color #black>Transaction Fees
****[#orange] <i><size:14><color #black>Digital Signatures
+++[#green] <i><size:14><color #white>**Distributed **Ledger:** (means **register or notebook**)**
+++[#green] <i><size:14><color #white>**Smart Contracts**
****[#orange] <i><size:14><color #black>**Definition:** A **smart contract** is an agreement between two parties in the form of computer code. Smart contracts are stored in the blockchain, \n<i><size:14><color #black>so they are part of the public ledger and cannot be changed. Smart contracts run on the blockchain and the transactions that happen are \n<i><size:14><color #black>processed by it, which means they can be sent automatically without a third party. The transactions only occur when specific conditions are met.
****[#orange] <i><size:14><color #black>Ethereum
*****[#yellow] <i><size:14>Solidity
*****[#yellow] <i><size:14>Vyper
****[#orange] <i><size:14><color #black>EOS
*****[#yellow] <i><size:14>C++
*****[#yellow] <i><size:14>WebAssembly
****[#orange] <i><size:14><color #black>Cardano
*****[#yellow] <i><size:14>Plutus
*****[#yellow] <i><size:14>Marlowe

**[#lightblue] <i><size:18>__**Blockchain Networks Type:**__\n<img:img_1.png>
***[#green]:<i><size:14><color #white>**Permissionless network:** allows access to any user to pseudo-anonymously join the
<i><size:14><color #white>network and become a node, without any restrictions. This particular kind of network is
<i><size:14><color #white>primarily used to exchange and mine cryptocurrencies.;

***[#green]:<i><size:14><color #white>**Permissioned network:**  restricts access to the network to certain nodes. In this type of
<i><size:14><color #white>network there can be rights restrictions. These private blockchain networks are controlled by a
<i><size:14><color #white>single organization that determines who can be a node. Pri- vate BC networks are partially
<i><size:14><color #white>decentralized because public access to them is restricted. __Due to the drawbacks of the above__
<i><size:14><color #white>networks, consortium and hybrid blockchains were developed.;

+++[#green] <i><size:14><color #white>**Public Blockchains**
****[#orange] <i><size:14><color #black>Bitcoin
****[#orange] <i><size:14><color #black>Ethereum
****[#orange] <i><size:14><color #black>Litecoin
****[#orange] <i><size:14><color #black>Cardano
****[#orange] <i><size:14><color #black>Polkadot
+++[#green] <i><size:14><color #white>**Private Blockchains**
****[#orange] <i><size:14><color #black>Hyperledger Fabric
****[#orange] <i><size:14><color #black>R3 Corda
****[#orange] <i><size:14><color #black>Quorum
+++[#green] <i><size:14><color #white>**Consortium Blockchains**
****[#orange] <i><size:14><color #black>Ripple
****[#orange] <i><size:14><color #black>Stellar

++[#lightblue] <i><size:14>Scalability Solutions
+++[#green] <i><size:14><color #white>**Layer 1 Solutions**
****[#orange] <i><size:14><color #black>Sharding
*****[#yellow] <i><size:14>Ethereum 2.0
*****[#yellow] <i><size:14>Zilliqa
*****[#yellow] <i><size:14>Polkadot
+++[#green] <i><size:14><color #white>**Layer 2 Solutions**
****[#orange] <i><size:14><color #black>State Channels
*****[#yellow] <i><size:14>Lightning Network (Bitcoin)
*****[#yellow] <i><size:14>Raiden Network (Ethereum)
****[#orange] <i><size:14><color #black>Plasma
*****[#yellow] <i><size:14>OmiseGO
****[#orange] <i><size:14><color #black>Rollups
*****[#yellow] <i><size:14>Optimistic Rollups
*****[#yellow] <i><size:14>ZK-Rollups

++[#lightblue] <i><size:14>Interoperability
+++[#green] <i><size:14><color #white>**Cross-Chain Communication**
****[#orange] <i><size:14><color #black>Polkadot
****[#orange] <i><size:14><color #black>Cosmos
****[#orange] <i><size:14><color #black>Wanchain
+++[#green] <i><size:14><color #white>**Atomic Swaps**
****[#orange] <i><size:14><color #black>Hashed Timelock Contracts (HTLC)
*****[#yellow] <i><size:14>Lightning Network (Bitcoin)
*****[#yellow] <i><size:14>Raiden Network (Ethereum)

++[#lightblue] <i><size:14>Security
+++[#green] <i><size:14><color #white>**51% Attack**
****[#orange] <i><size:14><color #black>In theory, a malicious user (attacker) can compromise consensus by controlling the\n<i><size:14><color #black>**51%** of the network, but consensus mechanisms are designed in a way that this attack\n<i><size:14><color #black>is practically impossible. There are different kinds of **consensus mechanisms** that are\n<i><size:14><color #black>invented to be used in cryptoeconomic systems.
+++[#green] <i><size:14><color #white>**Double Spending**
+++[#green] <i><size:14><color #white>**Replay Attacks**
+++[#green] <i><size:14><color #white>**Sybil Attacks**
+++[#green] <i><size:14><color #white>**Eclipse Attacks**
+++[#green] <i><size:14><color #white>**Smart Contract Vulnerabilities**
****[#orange] <i><size:14><color #black>Reentrancy Attacks
****[#orange] <i><size:14><color #black>Race Conditions
****[#orange] <i><size:14><color #black>Overflow and Underflow
@endmindmap

