zenuml

// this is zen-uml sequence diagram syntax
// here is link https://mermaid.js.org/syntax/zenuml.html
// for the different aws, gcp and azure shapes
//available for zenuml in sequence diagram

    title Annotators is @ sign
    @Actor Alice
    @Database Bob

    //ec2, sagemaker and s3 declaration
    @ec2 ec2
    @s3 S3
    @sagemaker Sagemaker

    Alice->Bob: Hi Bob
    Bob->Alice: Hi Alice
    Bob->Sagemaker:Visit mermaid website for details & check docs
    ec2->S3: Hi s3, how